import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {create,act} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
test('Single heartbeat waits3599/3600ms, cycles3600ms, skips initial pulse, cancels inactive/reduced/unmount and ignores ordinary rerenders',async()=>{
 let change,removed=false,now=0,id=0,r;const timers=new Map(),oldSet=setTimeout,oldClear=clearTimeout;globalThis.setTimeout=(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);const loops=[],jobs=[],values=[];
 const rn={Text:'Text',AccessibilityInfo:{isReduceMotionEnabled:async()=>false,addEventListener:(_e,fn)=>{change=fn;return{remove(){removed=true;}};}},Animated:{View:'AnimatedView',Value:class{setValue(v){values.push(v);}},timing(_v,c){jobs.push(c);return c;},delay(ms){return{delay:ms};},sequence:j=>j,loop:j=>{const a={j,start(){a.started=true;},stop(){a.stopped=true;}};loops.push(a);return a;}}};const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('./DominoTurnTitle.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>id==='react'?React:rn,m,m.exports);
 const render=async active=>act(async()=>{const e=React.createElement(m.exports.DominoTurnTitle,{active,label:'Waiting for your move'});r?r.update(e):r=create(e);});const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of timers)if(j.at<=now){timers.delete(key);j.fn();}});};
 try{await render(false);assert.equal(loops.length,0);assert.equal(r.root.findByType('Text').props.children,'Waiting for your move');await render(true);assert.equal(loops.length,1);assert.equal(loops[0].started,undefined);await tick(3599);assert.equal(loops[0].started,undefined);await render(true);assert.equal(loops.length,1);await tick(1);assert.equal(loops[0].started,true);assert.deepEqual(jobs.map(j=>j.duration),[210,210]);assert.deepEqual(loops[0].j.map(j=>j.delay??j.duration),[210,210,3180]);assert.equal(loops[0].j.reduce((sum,j)=>sum+(j.delay??j.duration),0),3600);assert.equal(jobs.filter(j=>j.toValue>1).length,1);assert.equal(jobs[0].toValue,1.07);
 await render(false);assert.equal(loops[0].stopped,true);assert.equal(values.at(-1),1);await render(true);await tick(1000);await render(false);await tick(4000);assert.equal(loops[1].started,undefined,'action before first beat cancels it');await act(()=>change(true));await render(true);assert.equal(loops.length,2);await act(()=>change(false));assert.equal(loops.length,3);await act(()=>r.unmount());r=null;await tick(4000);assert.equal(loops[2].started,undefined);assert.equal(loops[2].stopped,true);assert.equal(removed,true);assert.equal(timers.size,0);
 }finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}
});
