import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {create,act} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
function load(file,deps){const m={exports:{}};const code=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;new Function('require','module','exports',code)(id=>{if(!(id in deps))throw Error(id);return deps[id];},m,m.exports);return m.exports;}
function animation(reduced){const jobs=[];let progress;const rn={Text:'Text',View:'View',Pressable:'Pressable',AccessibilityInfo:{isReduceMotionEnabled:async()=>reduced},Easing:{cubic:x=>x,out:x=>x},Animated:{View:'AnimatedView',Value:class{interpolate(spec){return spec;}setValue(){}addListener(fn){progress=fn;return 1;}removeListener(){progress=null;}},timing(_v,config){const job={config,start(fn){job.finish=fn;},stop(){job.stopped=true;}};jobs.push(job);return job;}}};return {rn,jobs,progress(p){progress?.({value:p});}};}
test('Domino banners match gold, red and neutral styles, pause and reduced motion without hiding text',async()=>{
 const h=animation(false);let change;h.rn.AccessibilityInfo.addEventListener=(_event,fn)=>{change=fn;return{remove(){}};};h.rn.Animated.sequence=jobs=>({start(){jobs.forEach(j=>j.start());},stop(){jobs.forEach(j=>j.stop());}});
 const {DominoResultBanner}=load('./DominoResultBanner.tsx',{react:React,'react-native':h.rn});let r;const result={title:'YOU WIN',detail:'Two pair · Pot 100',tone:'win'};
 await act(async()=>{r=create(React.createElement(DominoResultBanner,{result,paused:false}));});assert.equal(h.jobs.length,3);assert.equal(r.root.findByProps({testID:'domino-result-banner'}).props.style.maxHeight,30);assert.equal(r.root.findAllByType('Text')[0].props.numberOfLines,1);assert.equal(r.root.findAllByType('Text')[0].props.style.color,'#F5F0E4');assert.equal(r.root.findAllByType('AnimatedView').length,17);assert.equal(h.jobs[2].config.duration,1200);const confetti=r.root.findByProps({testID:'domino-win-confetti'});assert.equal(confetti.props.pointerEvents,'none');assert.equal(r.root.findByProps({testID:'domino-result-banner'}).props.style.overflow,'hidden');assert.equal(confetti.findAllByType('AnimatedView').every(p=>p.props.style.opacity.outputRange.at(-1)===0),true);assert.equal(r.root.findByProps({testID:'domino-result-banner'}).props.style.borderColor,'#F5D58C');
 await act(()=>r.update(React.createElement(DominoResultBanner,{result,paused:true})));assert.ok(h.jobs.every(j=>j.stopped));assert.equal(r.root.findAllByType('AnimatedView').length,1);
 await act(()=>change(true));await act(()=>r.update(React.createElement(DominoResultBanner,{result,paused:false})));assert.equal(h.jobs.length,3);assert.equal(r.root.findAllByType('Text')[0].props.children,'YOU WIN');assert.equal(r.root.findAllByProps({testID:'domino-win-confetti'}).length,0);assert.equal(r.root.findAllByProps({testID:'domino-win-static-sparkles'}).length,1);
 for(const [tone,color] of [['loss','#FFB9AF'],['tie','#E4EADC']]){await act(()=>r.update(React.createElement(DominoResultBanner,{result:{...result,tone},paused:false})));assert.equal(r.root.findByProps({testID:'domino-result-banner'}).props.style.borderColor,color);assert.equal(r.root.findAllByType('AnimatedView').length,1);assert.equal(r.root.findAllByProps({testID:'domino-win-confetti'}).length,0);assert.equal(r.root.findAllByProps({testID:'domino-win-static-sparkles'}).length,0);}
 await act(()=>r.unmount());
});