import {useHeldResultTimer} from '../components/useHeldResultTimer.ts';
import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {create,act} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('./useDominoResultTransition.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(id=>id==='react'?React:{useHeldResultTimer},m,m.exports);
test('Domino waits2999/3000ms, hides on time, waits for landing/consumption, advances once and cancels pauses/exit',async()=>{
 const oldSet=setTimeout,oldClear=clearTimeout;let now=0,id=0,r,visible,calls=0;const jobs=new Map();globalThis.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>jobs.delete(id);
 const game={round:1,result:{winner:'human'}};function Probe({g=game,paused=false,settled=true}){visible=m.exports.useDominoResultTransition(g,paused,settled,()=>calls++);return null;}
 const render=async props=>act(()=>r?r.update(React.createElement(Probe,props)):r=create(React.createElement(Probe,props)));const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of jobs)if(j.at<=now){jobs.delete(key);j.fn();}});};
 try{await render({settled:false});await tick(2999);assert.equal(visible,true);assert.equal(calls,0);await tick(1);assert.equal(visible,false);assert.equal(calls,0);await render({});assert.equal(calls,1);await tick(9000);await render({});assert.equal(calls,1);
 const second={...game,round:2};await render({g:second});await tick(1000);await render({g:second,paused:true});await tick(5000);assert.equal(calls,1);await render({g:second});await tick(2999);assert.equal(calls,1);await tick(1);assert.equal(calls,2);
 await render({g:{...game,round:3}});await act(()=>r.unmount());r=null;await tick(4000);assert.equal(calls,2);assert.equal(jobs.size,0);await render({g:null});await tick(3000);assert.equal(calls,2);
 }finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}
});
test('Domino Hold pauses three-second result with remaining time, requires settlement and cancels on exit',async()=>{const oldSet=setTimeout,oldClear=clearTimeout,oldNow=Date.now;let now=0,id=0,r,visible,calls=0;const jobs=new Map(),pressed={current:false};globalThis.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>jobs.delete(id);Date.now=()=>now;const game={round:9,result:{winner:'human'}};function Probe({held=false,settled=true}){visible=m.exports.useDominoResultTransition(game,false,settled,()=>calls++,held,pressed);return null;}const render=async p=>act(()=>r?r.update(React.createElement(Probe,p)):r=create(React.createElement(Probe,p)));const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of jobs)if(j.at<=now){jobs.delete(key);j.fn();}});};try{await render({settled:false});await tick(1200);pressed.current=true;await render({held:true,settled:true});await tick(6000);assert.equal(visible,true);assert.equal(calls,0);pressed.current=false;await render({});await tick(1799);assert.equal(visible,true);assert.equal(calls,0);await tick(1);assert.equal(calls,1);await tick(9000);assert.equal(calls,1);await act(()=>r.unmount());r=null;assert.equal(jobs.size,0);}finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;Date.now=oldNow;}});
