import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire('C:/Development/Dominos Codex Pro/package.json'),React=require('react'),ts=require('typescript'),{act,create}=require('react-test-renderer');globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const app=fs.readFileSync(new URL('./App.tsx',import.meta.url),'utf8');const tree=ts.createSourceFile('App.tsx',app,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const shell=tree.statements.find(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='AppShell');const code=ts.transpileModule(shell.getText(tree)+'\nmodule.exports=AppShell;', {compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;
async function render(screen,bg){const m={exports:{}};const names=['React','useTheme','useGame','useNav','useTilt','Linking','useRef','useEffect','View','StatusBar','Background','SafeAreaView','Router','DayResetPrompt','FullScreenLoader','AppearanceSpinner'];const values=[React,()=>({theme:{colors:{bg},dark:true},ready:true}),()=>({loaded:true}),()=>({screen,openWatch(){}}),()=>({x:0,y:0}),{useURL:()=>null},React.useRef,React.useEffect,'View','StatusBar','Background',({children,...p})=>React.createElement('SafeAreaView',{...p,simulatedTopInset:24},children),'Router','DayResetPrompt','Loader','AppearanceSpinner'];new Function(...names,'module',code)(...values,m);let r;await act(()=>{r=create(React.createElement(m.exports));});return r;}
test('Poker and Blackjack lobbies match Domino status-area backing for every theme without changing safe-area edges',async()=>{for(const bg of ['#050607','#04130D','#172536'])for(const route of ['pokerLobby','blackjackLobby','computerGame','blackjackTable']){const r=await render(route,bg);assert.equal(r.root.findAllByType('View')[0].props.style.backgroundColor,'#081D1B');assert.equal(r.root.findAllByType('Background').length,0);assert.equal(r.root.findByType('StatusBar').props.style,'light');assert.deepEqual(r.root.findByType('SafeAreaView').props.edges,['top','bottom']);assert.equal(r.root.findByType('SafeAreaView').props.simulatedTopInset,24);await act(()=>r.unmount());}});
test('Home and Settings still retain selected appearance background',async()=>{for(const route of ['home','settings']){const r=await render(route,'#050607');assert.equal(r.root.findAllByType('View')[0].props.style.backgroundColor,'#050607');assert.equal(r.root.findAllByType('Background').length,1);await act(()=>r.unmount());}});
test('theme control is limited to score tracking routes, with all play routes excluded',async()=>{
 for(const route of ['newMatch','history','stats','settings','watch','watchHistory','howto','privacy']){
  const r=await render(route,'#050607');assert.equal(r.root.findAllByType('AppearanceSpinner').length,1);const control=r.root.findByProps({testID:'global-theme-control'});assert.equal(control.props.style.right,8);assert.equal(control.props.style.top,2);assert.deepEqual(r.root.findByType('SafeAreaView').props.edges,['top','bottom']);await act(()=>r.unmount());
 }
 for(const route of ['game','computerGame','pokerLobby','blackjackLobby','blackjackTable']){const r=await render(route,'#050607');assert.equal(r.root.findAllByType('AppearanceSpinner').length,0);assert.equal(r.root.findAllByProps({testID:'global-theme-control'}).length,0);await act(()=>r.unmount());}
 const home=await render('home','#050607');assert.equal(home.root.findAllByType('AppearanceSpinner').length,0);await act(()=>home.unmount());
});
