import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire('C:/Development/Dominos Codex Pro/package.json'),React=require('react'),ts=require('typescript'),{act,create}=require('react-test-renderer');globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const load=(file,deps)=>{const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>deps[id],m,m.exports);return m.exports;};const {THEMES}=load('../theme/themes.ts',{}),{STRINGS}=load('../i18n/strings.ts',{}),tracking=load('../state/trackingAppearanceStore.ts',{});const colors={yellow:'#D7A63D',green:'#65C59A',red:'#AA463B',blue:'#68B9F5'};
async function setup(){const creates=[],nav=[];const {NewMatchScreen}=load('./NewMatchScreen.tsx',{'../components/TrackingColorButton':{TrackingColorButton:'ColorButton'},'../state/trackingAppearanceStore':tracking,'../state/useTrackingAppearance':{useTrackingAppearance:()=>{const [p,set]=React.useState({teamAColor:'yellow',teamBColor:'red'});return {...p,setAppearance:patch=>set(prev=>({...prev,...patch})),cycleTeamColor:side=>set(prev=>{const key=side==='A'?'teamAColor':'teamBColor';return {...prev,[key]:tracking.nextTrackingColor(prev[key])};}),teamAColorValue:colors[p.teamAColor],teamBColorValue:colors[p.teamBColor]};}},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},react:React,'react-native':{TextInput:'Field',useWindowDimensions:()=>({height:640,width:320}),KeyboardAvoidingView:'View',Platform:{OS:'android'},Pressable:'Pressable',ScrollView:'ScrollView',Text:'Text',View:'View'},'expo-linear-gradient':{LinearGradient:'Gradient'},'../theme/ThemeContext':{useTheme:()=>({theme:THEMES.carbon,s:n=>n})},'../i18n/I18nContext':{useI18n:()=>({t:STRINGS.en})},'../state/GameContext':{useGame:()=>({createMatch:(...args)=>creates.push(args)})},'../nav/NavContext':{useNav:()=>({go:s=>nav.push(s),back:()=>nav.push('back')})},'../components/ui':{Button:'Button',Card:'Card',Field:'Field'},'../components/Header':{Header:'Header'},'../components/trackingLayout':load('../components/trackingLayout.ts'),'../components/MatchPresentation':{MatchTeamBadge:'Badge',MatchPanelBevel:'Bevel'}});let r;await act(()=>{r=create(React.createElement(NewMatchScreen));});return {r,creates,nav,close:()=>act(()=>r.unmount())};}
test('visual team cards preserve trimmed names players target and start navigation',async()=>{const h=await setup();try{const fields=h.r.root.findAllByType('Field'),values=[' Eagles ',' Ana ',' Luis ',' Sharks ',' Bea ',' Rigo '];await act(()=>fields.forEach((f,i)=>f.props.onChangeText(values[i])));await act(()=>h.r.root.findByType('Button').props.onPress());assert.deepEqual(h.creates,[[{name:'Eagles',players:['Ana','Luis']},{name:'Sharks',players:['Bea','Rigo']},100]]);assert.deepEqual(h.nav,['back','game']);}finally{await h.close();}});
test('custom points validation and default team names remain unchanged',async()=>{const h=await setup();try{const custom=h.r.root.findAllByType('Pressable').find(p=>p.findAllByType('Text').some(t=>t.props.children===STRINGS.en.custom));await act(()=>custom.props.onPress());const target=()=>h.r.root.findAllByType('Field').at(-1);await act(()=>target().props.onChangeText('0'));await act(()=>h.r.root.findByType('Button').props.onPress());assert.deepEqual(h.creates,[]);assert.deepEqual(h.nav,[]);await act(()=>target().props.onChangeText('120'));await act(()=>h.r.root.findByType('Button').props.onPress());assert.equal(h.creates[0][2],120);assert.equal(h.creates[0][0].name,'Team A');assert.equal(h.creates[0][1].name,'Team B');}finally{await h.close();}});

test('setup color buttons cycle all four choices without clearing entered names or creating a match',async()=>{
 const h=await setup();try{
  const values=['Eagles','Ana','Luis','Sharks','Bea','Rigo'];await act(()=>h.r.root.findAllByType('Field').forEach((f,i)=>f.props.onChangeText(values[i])));
  const buttons=()=>h.r.root.findAllByType('ColorButton');
  for(const team of [0,1]){const other=buttons()[1-team].props.value;const visited=[];for(let i=0;i<4;i++){await act(()=>buttons()[team].props.onPress());visited.push(buttons()[team].props.value);assert.equal(buttons()[1-team].props.value,other);}
   assert.deepEqual([...new Set(visited)].sort(),['blue','green','red','yellow']);}
  assert.deepEqual(h.r.root.findAllByType('Field').map(f=>f.props.value),values);assert.deepEqual(h.creates,[]);assert.deepEqual(h.nav,[]);
  await act(()=>h.r.root.findByType('Button').props.onPress());assert.deepEqual(h.creates[0],[{name:'Eagles',players:['Ana','Luis']},{name:'Sharks',players:['Bea','Rigo']},100]);
 }finally{await h.close();}
});
