import {useTableMusic} from '../sound/useTableMusic';
import {TableSettings} from '../computer/TableSettings';
import {useComputerGame} from '../computer/ComputerGameContext';
import {SeatChipPile} from './SeatChipPile';
import React,{useEffect,useState,useRef} from 'react';
import {AppState,BackHandler,Image,Modal,Pressable,ScrollView,Text,View,useWindowDimensions} from 'react-native';
import {TABLE as C} from '../computer/tableTheme';
import {Feather} from '@expo/vector-icons';
import {DominoTableBackground} from '../computer/DominoTableBackground';
import {DEALERS,DealerChoices} from './dealers';

import {ClassicPlayingCard as PlayingCard} from './ClassicPlayingCard';
import {GameSwitchButton,useTableGame} from '../poker/TableGameContext';
import {useI18n} from '../i18n/I18nContext';
import {useNav} from '../nav/NavContext';
import {useBlackjack} from './BlackjackContext';
import {dealerStep,hit,stand,value} from './engine';
import {BettingTray,DenominationChip} from './BettingTray';
import {ChipFlight} from './ChipFlight';
import type {Flight} from './ChipFlight';
import {FloatingAction} from './FloatingAction';
import {addStake,winReturn} from './presentation';
import {useBlackjackCardSound} from './useBlackjackCardSound';
import {BetWell} from './BetWell';
import {TurnPrompt} from './TurnPrompt';
import Svg,{Defs,LinearGradient,Stop,Rect,Path,Text as SvgText} from 'react-native-svg';
import {usePrefs} from '../state/PrefsContext';
function Button({label,onPress,disabled=false,id}:{label:string;onPress:()=>void;disabled?:boolean;id?:string}){
 return <Pressable testID={id} accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={{minHeight:44,padding:12,flex:1,borderRadius:12,borderWidth:1,borderColor:C.gold,backgroundColor:C.surface,alignItems:'center',justifyContent:'center',opacity:disabled?.4:1}}><Text style={{color:C.goldLight,fontWeight:'700',textAlign:'center'}}>{label}</Text></Pressable>;
}
function TotalBubble({children,id,color='#FFF0D0',down=false}:{children:React.ReactNode;id?:string;color?:string;down?:boolean}){return <View style={{alignItems:'center'}}><Text testID={id} style={{color,backgroundColor:'rgba(7,15,12,0.62)',borderRadius:12,paddingHorizontal:10,paddingVertical:4,fontSize:13,fontWeight:'700',overflow:'hidden'}}>{children}</Text><View style={down?{width:0,height:0,borderLeftWidth:5,borderRightWidth:5,borderTopWidth:5,borderLeftColor:'transparent',borderRightColor:'transparent',borderTopColor:'rgba(7,15,12,0.62)'}:{position:'absolute',left:-5,top:8,width:0,height:0,borderRightWidth:5,borderTopWidth:5,borderBottomWidth:5,borderRightColor:'rgba(7,15,12,0.62)',borderTopColor:'transparent',borderBottomColor:'transparent'}}/></View>;}
export function BlackjackScreen(){
 const {game:g,setGame,celebrated,setCelebrated,name,dealerId,setDealerId,chips,dealerChips=0,bet,wins,losses,pushes,startRound,refill}=useBlackjack();const {lang}=useI18n();const es=lang==='es';const {back,go}=useNav();const {enterMode,pokerName}=useTableGame();const {game:domino}=useComputerGame();const playerName=pokerName||name||domino?.playerName||(es?'Tú':'You');const {tileSound,ready,tableMusic,tableMusicTrack}=usePrefs();useTableMusic(ready&&tableMusic,tableMusicTrack);
 const {width,height}=useWindowDimensions();const compact=height<700;const cardWidth=Math.min(compact?54:68,(width-64)/4);
 const [settings,setSettings]=useState(false);const [rules,setRules]=useState(false);const [target,setTarget]=useState<'poker'|'domino'|null>(null);const [active,setActive]=useState(AppState.currentState==='active');
 const [picker,setPicker]=useState(false);const [betting,setBetting]=useState(!g);const [stake,setStake]=useState(0);
 const [selectedChips,setSelectedChips]=useState<number[]>([]);
 const stakeRef=useRef(0);const generation=useRef(0);const root=useRef<View>(null);const pot=useRef<View>(null);const balance=useRef<View>(null);const dealerBalance=useRef<View>(null);const serial=useRef(0);const launched=useRef<typeof g>(null);
 const [flights,setFlights]=useState<Flight[]>([]);const [winProgress,setWinProgress]=useState(0);const [footerHeight,setFooterHeight]=useState(40);const [rootHeight,setRootHeight]=useState(height);
 const dealerWon=g?.result==='dealer';const payout=dealerWon||g?.result==='push'?(bet??0):winReturn(g?.result??null,bet??0);const pendingWin=!!g?.result&&payout>0&&celebrated!==g;
 const visibleStake=betting?stake:g?.result&&!pendingWin?0:bet??0;
 const restoredChips:number[]=[];let remainingStake=visibleStake;for(const denomination of [1000,500,100,50,20,10])while(remainingStake>=denomination){restoredChips.push(denomination);remainingStake-=denomination;}
 const visibleChips=Math.round((chips??1000)-(pendingWin&&!dealerWon?payout*(1-(launched.current===g?winProgress:0)):0));
 const launch=(amount:number,kind:'bet'|'win',source:React.RefObject<View|null>)=>{
  const token=generation.current;
  const add=(rx:number,ry:number,sx:number,sy:number,tx:number,ty:number)=>{if(kind==='bet'&&token!==generation.current)return;setFlights(items=>[...items,{id:++serial.current,amount,kind,from:{x:sx-rx,y:sy-ry},to:{x:tx-rx,y:ty-ry}}]);};
  const destination=kind==='win'?(dealerWon?dealerBalance:balance):pot;
  if(root.current&&source.current&&destination.current)root.current.measureInWindow((rx,ry)=>source.current?.measureInWindow((sx,sy,sw,sh)=>destination.current?.measureInWindow((tx,ty,tw,th)=>add(rx,ry,sx+sw/2,sy+sh/2,tx+tw/2,ty+th/2))));
  else add(0,0,width/2,rootHeight-footerHeight-65,kind==='win'?54:width/2,kind==='win'?(dealerWon?heroHeight+30:rootHeight-footerHeight-180):rootHeight-footerHeight-140);
 };
 const [presented,setPresented]=useState<typeof g>(null);const dealing=g!==presented;const paused=settings||rules||!!target||picker||betting||!active;
 useBlackjackCardSound(g,ready&&tileSound,paused);
 const dealer=DEALERS.find(o=>o.id===dealerId)??DEALERS[0];const heroHeight=compact?130:160;
 useEffect(()=>{const sub=AppState.addEventListener('change',s=>setActive(s==='active'));const nav=BackHandler.addEventListener('hardwareBackPress',()=>{if(rules)setRules(false);else if(target)setTarget(null);else back();return true;});return()=>{sub.remove();nav.remove();};},[back,rules,target]);
 useEffect(()=>{if(!g||paused)return;const timer=setTimeout(()=>setPresented(g),700);return()=>clearTimeout(timer);},[g,paused]);
 useEffect(()=>{if(!g||g.phase!=='dealer'||paused||dealing)return;const timer=setTimeout(()=>setGame(current=>current===g?dealerStep(g):current),850);return()=>clearTimeout(timer);},[g,paused,dealing,setGame]);
 useEffect(()=>{if(!pendingWin||!g||dealing||paused||launched.current===g)return;launched.current=g;setWinProgress(0);launch(payout,'win',pot);},[g,pendingWin,dealing,paused]);
 useEffect(()=>{if(!g?.result){setWinProgress(0);launched.current=null;}},[g?.result]);
 const chooseChip=(n:number,source:React.RefObject<View|null>)=>{if(rules||picker||target||!active||pendingWin||(g&&!g.result))return;if(!betting){stakeRef.current=0;setBetting(true);}const next=addStake(stakeRef.current,n,chips);if(next!==stakeRef.current){stakeRef.current=next;setStake(next);setSelectedChips(items=>[...(betting?items:[]),n]);launch(n,'bet',source);}};
 const deal=()=>{if(stake>=10&&stake<=chips){generation.current++;setFlights([]);startRound(stakeRef.current);setBetting(false);}};
 const cardsVisible=!!g&&!betting&&!(g.result&&celebrated===g);const p=value(g?.player??[]);const enabled=g?.phase==='player'&&!paused&&!dealing;const hidden=g?.phase==='player';
 const result=g?.result==='blackjack'?'Blackjack!':g?.result==='player'?(es?'Ganaste':'You win'):g?.result==='push'?(es?'Empate':'Push'):(p.bust?(es?'Te pasaste · gana el dealer':'Bust · dealer wins'):(es?'Gana el dealer':'Dealer wins'));
 const send=(action:typeof hit)=>{if(enabled&&g)setGame(current=>current===g?action(g):current);};
 return <View ref={root} collapsable={false} onLayout={e=>setRootHeight(e.nativeEvent.layout.height)} style={{flex:1,backgroundColor:C.background,overflow:'hidden'}}>
 <View style={{height:48,flexDirection:'row',alignItems:'center',paddingHorizontal:6,borderBottomWidth:1,borderBottomColor:C.line}}><Pressable accessibilityRole="button" accessibilityLabel={es?'Volver':'Back'} onPress={back} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Feather name="arrow-left" size={20} color={C.ivory}/></Pressable><View style={{flex:1,alignItems:'center'}}><Text style={{color:C.ivory,fontSize:16,letterSpacing:3,fontWeight:'600'}}>BLACKJACK</Text><Text style={{color:C.gold,fontSize:9,letterSpacing:1.5}}>SOCIAL CLUB · 3:2</Text></View><Pressable accessibilityRole="button" accessibilityLabel={es?'Ajustes':'Settings'} onPress={()=>setSettings(true)} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Feather name="more-vertical" size={20} color={C.gold}/></Pressable></View>
 <View testID="blackjack-table-surface" style={{flex:1,minHeight:0}}>
 <ScrollView contentContainerStyle={{paddingHorizontal:14,paddingBottom:12,flexGrow:1}}>
 <View style={{flex:1,minHeight:compact?445:540,paddingBottom:130,gap:12,justifyContent:'flex-start'}}>
 <View pointerEvents="none" style={{position:'absolute',top:0,bottom:0,left:5,right:12,overflow:'hidden'}}><DominoTableBackground opponentHeight={heroHeight} gift={null} es={es} finished={!!g?.result}/></View>
 <View ref={dealerBalance} collapsable={false} style={{position:'absolute',left:42,top:heroHeight-65,zIndex:12}}><SeatChipPile testID="blackjack-dealer-pile" name={dealer.name} hideName totalAbove amount={dealerChips-(pendingWin&&dealerWon?payout*(1-(launched.current===g?winProgress:0)):0)}/></View>
 <View ref={balance} collapsable={false} style={{position:'absolute',left:12,bottom:56,zIndex:12}}><SeatChipPile testID="blackjack-player-pile" name={playerName} amount={visibleChips}/></View>
 <View pointerEvents="none" style={{position:'absolute',top:heroHeight+cardWidth*1.43+67,left:20,right:20,height:85,alignItems:'center'}}><Svg width="100%" height={85} viewBox="0 0 300 85"><Path d="M135 20L131 8L141 14L150 4L159 14L169 8L165 20Z M136 24H164" fill="#8B9A71" opacity={.28} stroke="#8B9A71" strokeWidth={1}/><Path d="M135 19L131 7L141 13L150 3L159 13L169 7L165 19Z M136 23H164" fill="#94A49B" stroke="#415D50" strokeWidth={1.3}/><SvgText x={150} y={51.2} textAnchor="middle" fill="#8B9A71" opacity={.28} fontSize={23} fontWeight="700" letterSpacing={2}>BLACKJACK</SvgText><SvgText x={150} y={50} textAnchor="middle" fill="#94A49B" stroke="#415D50" strokeWidth={.65} opacity={.88} fontSize={23} fontWeight="700" letterSpacing={2}>BLACKJACK</SvgText><SvgText x={150} y={70.2} textAnchor="middle" fill="#8B9A71" opacity={.25} fontSize={11} fontWeight="600" letterSpacing={3}>SOCIAL CLUB</SvgText><SvgText x={150} y={69} textAnchor="middle" fill="#94A49B" stroke="#415D50" strokeWidth={.35} opacity={.85} fontSize={11} fontWeight="600" letterSpacing={3}>SOCIAL CLUB</SvgText></Svg></View>
 <View style={{height:heroHeight,flexDirection:'row',alignItems:'flex-end',gap:5}}>
 <View testID="blackjack-balance" style={{width:70,alignSelf:'flex-start',marginTop:10,gap:4}}><Text style={{color:C.goldLight,fontSize:12}}>{es?'Ganadas':'Won'} {wins??0}</Text><Text style={{color:C.ivory,fontSize:12}}>{es?'Perdidas':'Lost'} {losses??0}</Text></View>
 <Pressable testID="blackjack-dealer" accessibilityRole="button" accessibilityLabel={es?`Cambiar dealer: ${dealer.name}`:`Change dealer: ${dealer.name}`} onPress={()=>setPicker(true)} style={{flex:1,height:heroHeight}}><Image source={dealer.image} resizeMode="contain" style={{width:'100%',height:heroHeight}}/></Pressable>
 <View style={{width:70,alignSelf:'flex-start',marginTop:8,gap:6}}><GameSwitchButton targetMode="poker" onSelect={()=>setTarget('poker')}/><GameSwitchButton whiteDomino targetMode="domino" onSelect={()=>setTarget('domino')}/></View></View>
 <View style={{alignItems:'center',gap:6,marginTop:18}}>
 <View style={{position:'relative',width:Math.min((g?.dealer.length??0)*(cardWidth+6)-6,width-70),minWidth:cardWidth,alignItems:'center'}}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{maxWidth:'100%'}} contentContainerStyle={{gap:6}}>{cardsVisible&&g?.dealer.map((card,i)=><PlayingCard key={`${i}-${card.rank}${card.suit}`} card={hidden&&i===1?undefined:card} back={hidden&&i===1} width={cardWidth} delay={i<2?i*140:0} originX={80}/>)}</ScrollView>
 <View style={{position:'absolute',top:-5,right:-24}}>{cardsVisible&&!hidden&&g?<TotalBubble id="dealer-total">{String(value(g.dealer).total)}</TotalBubble>:<Text testID="dealer-total">{''}</Text>}</View></View></View>
 <View style={{flex:1,justifyContent:'flex-end',alignItems:'center',gap:7}}><View testID="blackjack-hand-message" style={{minHeight:28,paddingVertical:4,alignSelf:'stretch',paddingHorizontal:18}}><TurnPrompt visible={!!g&&!betting&&active&&!rules&&!settings&&!picker&&!target} label={enabled?(es?'Tu turno':'Your turn'):dealing?(es?'Repartiendo…':'Dealing…'):g?.result?result:g?.phase==='dealer'?(es?'Turno del dealer':'Dealer’s turn'):''}/></View><View style={{position:'relative',width:Math.min((g?.player.length??0)*(cardWidth+6)-6,width-70),minWidth:cardWidth,alignItems:'center'}}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{maxWidth:'100%'}} contentContainerStyle={{gap:6}}>{cardsVisible&&g?.player.map((card,i)=><PlayingCard key={`${i}-${card.rank}${card.suit}`} card={card} width={cardWidth} delay={i<2?i*140:0} originX={80}/>)}</ScrollView>{cardsVisible&&g&&g.player.length>0?<View style={{position:'absolute',top:-5,right:-24}}><TotalBubble id="blackjack-player-total" color={p.bust?'#FFB9AF':'#FFF0D0'}>{p.total}{p.soft?(es?' · suave':' · soft'):''}</TotalBubble></View>:null}</View></View>
 </View>
 </ScrollView>
 <View style={{position:'absolute',bottom:12,left:(width-110)/2,width:110,alignItems:'center',gap:0,zIndex:12}}><View ref={pot} collapsable={false} testID="blackjack-bet-spot" style={{height:74,width:110,alignItems:'center',justifyContent:'center'}}><BetWell/><View style={{height:48,width:66,marginTop:12}}>{(visibleStake>0?(selectedChips.length?selectedChips:restoredChips):[]).slice(-6).map((amount,i)=><View key={i} style={{position:'absolute',left:i*3,bottom:i*5}}><DenominationChip amount={amount}/></View>)}</View><View style={{position:'absolute',top:-17,alignSelf:'center'}}><TotalBubble id="blackjack-bet-total" down>{'$'+visibleStake.toLocaleString()}</TotalBubble></View></View><Pressable accessibilityRole="button" disabled={!(!g||!!g.result)||pendingWin||rules||picker||!!target||!active} onPress={()=>{if(!g||g.result){generation.current++;stakeRef.current=0;setStake(0);setSelectedChips([]);setBetting(true);setFlights(f=>f.filter(x=>x.kind!=='bet'));}}} style={{padding:8}}><Text style={{color:C.muted,fontSize:12}}>{es?'Limpiar':'Clear'}</Text></Pressable></View>
 </View>
 <View onLayout={e=>setFooterHeight(e.nativeEvent.layout.height)} style={{paddingHorizontal:12,paddingTop:22,paddingBottom:10,minHeight:87,backgroundColor:'#704329'}}>
 <View pointerEvents="none" style={{position:'absolute',top:0,bottom:0,left:0,right:0}}><Svg width="100%" height="100%" viewBox="0 0 400 100" preserveAspectRatio="none"><Defs><LinearGradient id="bjWood" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#4D2C1C"/><Stop offset="0.4" stopColor="#865335"/><Stop offset="1" stopColor="#603922"/></LinearGradient><LinearGradient id="bjLipShadow" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#080F0B" stopOpacity="0.8"/><Stop offset="1" stopColor="#080F0B" stopOpacity="0"/></LinearGradient></Defs><Rect width="400" height="100" fill="url(#bjWood)"/>{[33,48,66,82,94].map((y,i)=><Path key={y} d={`M0 ${y} Q100 ${y-4} 210 ${y+1} T400 ${y-2}`} fill="none" stroke={i%2?'#B88352':'#321B11'} strokeOpacity="0.19" strokeWidth="1"/>)}<Path d="M0 0 H400 V7 Q200 22 0 7 Z" fill="#0C271C"/><Path d="M0 7 Q200 22 400 7 L400 28 Q200 40 0 28 Z" fill="url(#bjLipShadow)"/><Path d="M0 7 Q200 22 400 7" fill="none" stroke="#AF9362" strokeOpacity="0.38" strokeWidth="1.2"/></Svg></View>
 {chips<10&&(!g||g.result)?<Button id="blackjack-refill" label={es?'Agregar 1,000 fichas':'Add 1,000 chips'} onPress={()=>{refill();stakeRef.current=0;setStake(0);setSelectedChips([]);setBetting(true);}}/>:null}
 <BettingTray stake={visibleStake} balance={chips} es={es} canBet={(!g||!!g.result)&&!pendingWin&&!rules&&!picker&&!target&&active} onChip={chooseChip} onClear={()=>{if(!g||g.result){generation.current++;stakeRef.current=0;setStake(0);setSelectedChips([]);setBetting(true);setFlights(f=>f.filter(x=>x.kind!=='bet'));}}}/>
 </View>

 <FloatingAction id="blackjack-deal" label="DEAL" side="right" bottom={footerHeight+60} visible={betting&&stake>=10&&stake<=chips&&!rules&&!picker&&active&&!target} enabled onPress={deal}/>
 <FloatingAction id="blackjack-hit" label="HIT" side="left" bottom={footerHeight+6} visible={!!enabled} enabled={!!enabled} onPress={()=>send(hit)}/>
 <FloatingAction id="blackjack-stand" label="STAND" side="right" bottom={footerHeight+6} visible={!!enabled} enabled={!!enabled} onPress={()=>send(stand)}/>
 {flights.map(f=><ChipFlight key={f.id} flight={f} sound={ready&&tileSound} paused={rules||picker||!!target||!active} onProgress={f.kind==='win'?setWinProgress:undefined} onComplete={()=>{setFlights(items=>items.filter(x=>x.id!==f.id));if(f.kind==='win'&&g){setWinProgress(1);setCelebrated(g);}}}/>)}
 <Modal visible={picker} transparent animationType="fade" onRequestClose={()=>setPicker(false)}><View style={{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(2,12,10,.84)'}}><View style={{padding:20,gap:16,backgroundColor:C.surface,borderRadius:22}}><Text style={{color:C.goldLight,fontSize:22}}>{es?'Elige tu dealer':'Choose your dealer'}</Text><DealerChoices selected={dealer.id} onSelect={id=>{setDealerId(id);setPicker(false);}}/><Button label={es?'Cerrar':'Close'} onPress={()=>setPicker(false)}/></View></View></Modal>
 <Modal visible={rules} transparent animationType="fade" onRequestClose={()=>setRules(false)}><View style={{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'center',padding:24}}><View style={{backgroundColor:C.surface,padding:22,borderRadius:18,gap:16,maxHeight:'90%'}}><Text style={{color:C.goldLight,fontSize:20}}>{es?'Reglas de Blackjack':'Blackjack rules'}</Text><ScrollView style={{flexShrink:1}}><Text style={{color:C.ivory,lineHeight:23}}>{es?'Acércate a 21 sin pasarte. J/Q/K valen 10; el as vale 1 u 11. As y carta de valor 10 en las dos primeras cartas forman blackjack natural y ganan salvo otro natural (empate). Pedir añade una carta; plantarse inicia el turno del dealer. El dealer pide hasta 16 y se planta en todo 17, incluido el suave. Si te pasas, pierdes aunque el dealer pudiera pasarse. Totales iguales empatan. Una baraja nueva por ronda. Fichas virtuales: victoria paga 1:1 y blackjack natural 3:2. Sin dividir, doblar ni seguro.':'Reach 21 without going over. J/Q/K count 10; an ace counts 1 or 11. An ace and a ten-value card in the initial two cards are a natural blackjack, winning unless the dealer also has a natural (push). Hit adds a card; stand starts the dealer turn. The dealer hits through 16 and stands on all 17, including soft 17. Player bust loses immediately. Equal totals push. Fresh single deck each round. Virtual chips: wins pay 1:1 and natural blackjack 3:2. No splitting, doubling or insurance.'}</Text></ScrollView><Button id="blackjack-close-rules" label={es?'Cerrar':'Close'} onPress={()=>setRules(false)}/></View></View></Modal>
 <Modal visible={!!target} transparent animationType="fade" onRequestClose={()=>setTarget(null)}><View style={{flex:1,backgroundColor:'rgba(2,12,10,.84)',justifyContent:'center',padding:26}}><View accessibilityViewIsModal style={{backgroundColor:C.surface,borderRadius:24,padding:24,borderWidth:1,borderColor:C.line,gap:18}}>
 <Text style={{color:C.ivory,fontSize:23,fontWeight:'600'}}>{es?`¿Quieres cambiar a ${target==='poker'?'póker':'dominó'}?`:`Switch to ${target==='poker'?'poker':'dominoes'}?`}</Text>
 <Text style={{color:C.muted,fontSize:15,lineHeight:23}}>{es?'Tu partida actual quedará pausada para continuar al volver.':'Your current game will pause so you can continue when you return.'}</Text>
 <View style={{flexDirection:'row',gap:12}}><Pressable accessibilityRole="button" onPress={()=>setTarget(null)} style={{flex:1,padding:15,borderRadius:12,backgroundColor:C.raised,alignItems:'center'}}><Text style={{color:C.ivory}}>{es?'Cancelar':'Cancel'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{if(target){enterMode(target);setTarget(null);go('computerGame');}}} style={{flex:1,padding:15,borderRadius:12,backgroundColor:C.gold,alignItems:'center'}}><Text style={{color:C.background,fontWeight:'700'}}>{es?'Cambiar':'Switch'}</Text></Pressable></View>
 </View></View></Modal>
 <TableSettings matching={false} visible={settings} es={es} onClose={()=>setSettings(false)} onRules={()=>{setSettings(false);setRules(true);}}/>
 </View>;
}
