import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {NaturalCardAccent} from './NaturalCardAccent';
import {TableStamp} from './TableFinish';
import {ResultBanner} from './ResultBanner';
import {describeResult,RESULT_READ_MS} from './resultPresentation';
import {useTableMusic} from '../sound/useTableMusic';
import {TableSettings} from '../computer/TableSettings';
import {useComputerGame} from '../computer/ComputerGameContext';
import {DealerChipRack} from './DealerChipRack';
import {ResultHoldButton} from '../components/ResultHoldButton';
import {useHeldResultTimer} from '../components/useHeldResultTimer';
import {dealerRackWidth,dealerRackChannelPoint} from './dealerRackPresentation';
import {chipAmounts} from './chipAmounts';
import React,{useEffect,useState,useRef} from 'react';
import {AppState,BackHandler,Image,Modal,Pressable,ScrollView,Text,View,useWindowDimensions} from 'react-native';
import {TABLE as C} from '../computer/tableTheme';
import {Feather} from '@expo/vector-icons';
import {DominoTableBackground} from '../computer/DominoTableBackground';
import {DEALERS,DealerChoices} from './dealers';

import {ClassicPlayingCard as PlayingCard} from './ClassicPlayingCard';
import {GameSwitchButton,useTableGame} from '../poker/TableGameContext';
import {useI18n} from '../i18n/I18nContext';
import {useNav} from '../nav/NavContext';
import {useBlackjack} from './BlackjackContext';
import {dealerStep,hit,stand,value} from './engine';
import {BettingTray,DenominationChip,BANKROLL_CHIP_SCALE} from './BettingTray';
import {ChipFlight} from './ChipFlight';
import type {Flight} from './ChipFlight';
import {FloatingAction} from './FloatingAction';
import {addStake,winReturn} from './presentation';
import {useBlackjackCardSound} from './useBlackjackCardSound';
import {BetWell} from './BetWell';
import {TurnPrompt} from './TurnPrompt';
import Svg,{Defs,LinearGradient,Stop,Rect,Path,Text as SvgText} from 'react-native-svg';
import {usePrefs} from '../state/PrefsContext';
function Button({label,onPress,disabled=false,id}:{label:string;onPress:()=>void;disabled?:boolean;id?:string}){
 return <Pressable testID={id} accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={{minHeight:44,padding:12,flex:1,borderRadius:12,borderWidth:1,borderColor:C.gold,backgroundColor:C.surface,alignItems:'center',justifyContent:'center',opacity:disabled?.4:1}}><Text style={{color:C.goldLight,fontWeight:'700',textAlign:'center'}}>{label}</Text></Pressable>;
}
function TotalBubble({children,id,color='#FFF0D0',down=false}:{children:React.ReactNode;id?:string;color?:string;down?:boolean}){return <View style={{alignItems:'center'}}><Text testID={id} style={{color,backgroundColor:'rgba(7,15,12,0.62)',borderRadius:12,paddingHorizontal:10,paddingVertical:4,fontSize:13,fontWeight:'700',overflow:'hidden'}}>{children}</Text><View style={down?{width:0,height:0,borderLeftWidth:5,borderRightWidth:5,borderTopWidth:5,borderLeftColor:'transparent',borderRightColor:'transparent',borderTopColor:'rgba(7,15,12,0.62)'}:{position:'absolute',left:-5,top:8,width:0,height:0,borderRightWidth:5,borderTopWidth:5,borderBottomWidth:5,borderRightColor:'rgba(7,15,12,0.62)',borderTopColor:'transparent',borderBottomColor:'transparent'}}/></View>;}
export function BlackjackScreen(){
 const {game:g,setGame,collected,setCollected,celebrated,setCelebrated,name,dealerId,setDealerId,chips,dealerChips=0,bet,wins,losses,pushes,canDouble,doubleDown,repeatBet,startRound,refill}=useBlackjack();const {lang}=useI18n();const es=lang==='es';const {back,go}=useNav();const {enterMode,pokerName}=useTableGame();const {game:domino}=useComputerGame();const playerName=pokerName||name||domino?.playerName||(es?'Tú':'You');const {tileSound,ready,tableMusic,tableMusicTrack}=usePrefs();useTableMusic(ready&&tableMusic,tableMusicTrack);
 const {width,height}=useWindowDimensions();const insets=useSafeAreaInsets();const usableHeight=height-insets.top-insets.bottom;const compact=usableHeight<720;const cardWidth=Math.min(compact?54:68,(width-64)/4);
 const [settings,setSettings]=useState(false);const [rules,setRules]=useState(false);const [target,setTarget]=useState<'poker'|'domino'|null>(null);const [active,setActive]=useState(AppState.currentState==='active');
 const [holding,setHolding]=useState(false);const resultHold=useRef(false);const deferredCollections=useRef(new Set<number>());const [picker,setPicker]=useState(false);const [betting,setBetting]=useState(!g);const [stake,setStake]=useState(0);
 const [selectedChips,setSelectedChips]=useState<number[]>([]);const selectionIndex=useRef(0);const [landed,setLanded]=useState<Set<number>>(new Set());
 const stakeRef=useRef(0);const generation=useRef(0);const root=useRef<View>(null);const pot=useRef<View>(null);const balance=useRef<View>(null);const dealerBalance=useRef<View>(null);const serial=useRef(0);const launched=useRef<typeof g>(null);
 const [flights,setFlights]=useState<(Flight&{order?:number;generation:number;silent?:boolean})[]>([]);const [winProgress,setWinProgress]=useState(0);const [footerHeight,setFooterHeight]=useState(40);const [rootHeight,setRootHeight]=useState(height);
 const winRemaining=useRef(0),winTotal=useRef(0),winAmounts=useRef(new Map<number,number>()),winProgresses=useRef(new Map<number,number>()),winDone=useRef(new Set<number>());
 const updateWinProgress=()=>setWinProgress(Math.min(1,[...winProgresses.current].reduce((sum,[id,p])=>sum+(winAmounts.current.get(id)??0)*p,0)/(winTotal.current||1)));
 const dealerWon=g?.result==='dealer';const payout=dealerWon||g?.result==='push'?(bet??0):winReturn(g?.result??null,bet??0);const pendingWin=!!g?.result&&payout>0&&celebrated!==g;
 const visibleStake=betting?stake:g?.result&&(collected===g||!pendingWin)?0:bet??0;
 const restoredChips=chipAmounts(visibleStake);const ordered=selectedChips.length>0&&selectedChips.reduce((sum,n)=>sum+n,0)===visibleStake;const betSequence=ordered?selectedChips:restoredChips;const betLayerStep=Math.min(2,8/Math.max(1,Math.ceil(betSequence.length/3)-1));
 const visibleChips=Math.round((chips??3000)-(betting?stake:0)-(pendingWin&&!dealerWon?payout*(1-(collected===g?1:launched.current===g?winProgress:0)):0));
 useEffect(()=>()=>{resultHold.current=false;generation.current++;},[]);
 useEffect(()=>{resultHold.current=false;setHolding(false);deferredCollections.current.clear();},[g]);
 useEffect(()=>{if(settings||rules||picker||target||!active){resultHold.current=false;setHolding(false);}},[settings,rules,picker,target,active]);
 const launch=(amount:number,kind:'bet'|'win',source:React.RefObject<View|null>,order?:number,rackDenomination?:number,silent=false)=>{
  const token=generation.current;
  const add=(rx:number,ry:number,sx:number,sy:number,tx:number,ty:number)=>{if(token!==generation.current)return;const id=++serial.current;if(kind==='win'){winAmounts.current.set(id,amount);winProgresses.current.set(id,0);}setFlights(items=>[...items,{id,amount,kind,order,generation:token,rackDenomination,silent,landingScale:kind==='bet'?BANKROLL_CHIP_SCALE:rackDenomination?dealerRackWidth(width,height)*.12/50:undefined,facingPlayer:kind==='bet',holdUntilLanding:kind==='bet',from:{x:sx-rx,y:sy-ry},to:{x:tx-rx,y:ty-ry}}]);};
  const destination=kind==='win'?(dealerWon?dealerBalance:balance):pot;
  if(root.current&&source.current&&destination.current)root.current.measureInWindow((rx,ry)=>source.current?.measureInWindow((sx,sy,sw,sh)=>destination.current?.measureInWindow((tx,ty,tw,th)=>{if(kind==='bet'&&order!==undefined){const step=Math.min(2,8/Math.max(1,Math.ceil(selectionIndex.current/3)-1));const x=order%3===2?29:3+(order%3)*52;const y=Math.floor(order/3)*step+(order%3===2?12:0);add(rx,ry,sx+sw/2,sy+sh/2,tx+(tw-104)/2+x+25*BANKROLL_CHIP_SCALE,ty+(th-70)/2+70-y-21*BANKROLL_CHIP_SCALE);}else if(rackDenomination!==undefined){const target=dealerRackChannelPoint(rackDenomination,{x:tx,y:ty,width:tw,height:th});add(rx,ry,sx+sw/2,sy+sh/2,target.x,target.y);}else add(rx,ry,sx+sw/2,sy+sh/2,tx+tw/2,ty+th/2);})));
  else if(rackDenomination!==undefined){const rackWidth=dealerRackWidth(width,height);const target=dealerRackChannelPoint(rackDenomination,{x:(width-rackWidth)/2,y:48+heroHeight+(compact?8:12)+(compact?-20:-16),width:rackWidth,height:48});add(0,0,width/2,rootHeight-footerHeight-65,target.x,target.y);}else add(0,0,width/2,rootHeight-footerHeight-65,kind==='win'?(dealerWon?54:width/2):width/2,kind==='win'?(dealerWon?heroHeight+30:rootHeight-footerHeight+12):rootHeight-footerHeight-140);
 };
 const [presented,setPresented]=useState<typeof g>(null);const dealing=g!==presented;const paused=settings||rules||!!target||picker||betting||!active;
 useBlackjackCardSound(g,ready&&tileSound,paused);
 const dealer=DEALERS.find(o=>o.id===dealerId)??DEALERS[0];const heroHeight=compact?105:Math.min(165,usableHeight*.20);
 // Match the visible resting figure, including contain letterboxing in narrow seats.
 const restContentHeight=Math.min(Math.max(44,width-200)*1.28/1.5,heroHeight*1.10);
 const restVisibleHeight=restContentHeight*327/400;
 const restHeadTop=-heroHeight*.04+(heroHeight*1.10-restContentHeight)/2+restContentHeight*17/400;
 const dealerFigureHeight=restVisibleHeight*1374/(dealer.id==='elena'?1335:1328);
 const dealerFigureTop=restHeadTop-dealerFigureHeight*(dealer.id==='elena'?16:8)/1374;
 useEffect(()=>{const sub=AppState.addEventListener('change',s=>setActive(s==='active'));const nav=BackHandler.addEventListener('hardwareBackPress',()=>{if(rules)setRules(false);else if(target)setTarget(null);else back();return true;});return()=>{sub.remove();nav.remove();};},[back,rules,target]);
 useEffect(()=>{if(!g||paused)return;const timer=setTimeout(()=>setPresented(g),700);return()=>clearTimeout(timer);},[g,paused]);
 useEffect(()=>{if(!g||g.phase!=='dealer'||paused||dealing)return;const timer=setTimeout(()=>setGame(current=>current===g?dealerStep(g):current),850);return()=>clearTimeout(timer);},[g,paused,dealing,setGame]);
 const readDone=useHeldResultTimer(pendingWin&&g&&!dealing?g:null,paused,RESULT_READ_MS,holding,resultHold,true)?g:null;
 useEffect(()=>{if(!pendingWin||!g||dealing||paused||holding||resultHold.current||collected===g||launched.current===g)return;launched.current=g;setWinProgress(0);const amounts=dealerWon?chipAmounts(payout):[payout];winRemaining.current=amounts.length;winTotal.current=payout;winAmounts.current.clear();winProgresses.current.clear();winDone.current.clear();amounts.forEach((amount,i)=>launch(amount,'win',pot,undefined,dealerWon?amount:undefined,i>0));},[g,pendingWin,dealing,paused,collected,holding]);
 useEffect(()=>{if(!g?.result||celebrated===g||collected!==g||readDone!==g||paused||holding||resultHold.current)return;setCelebrated(g);setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());stakeRef.current=0;setStake(0);setBetting(true);},[g,collected,readDone,paused,celebrated,setCelebrated,holding]);
 useEffect(()=>{if(!g?.result){setWinProgress(0);launched.current=null;}},[g?.result]);
 const finishCollection=(f:typeof flights[number])=>{if(f.generation!==generation.current)return;if(f.kind==='win'&&resultHold.current){deferredCollections.current.add(f.id);return;}const order=f.order;if(f.kind==='bet'&&order!==undefined)setLanded(previous=>new Set(previous).add(order));setFlights(items=>items.filter(x=>x.id!==f.id));if(f.kind==='win'&&g&&launched.current===g&&!winDone.current.has(f.id)){winDone.current.add(f.id);winProgresses.current.set(f.id,1);winRemaining.current--;updateWinProgress();if(winRemaining.current===0){setWinProgress(1);setCollected(g);}}};
 const releaseHold=()=>{resultHold.current=false;setHolding(false);const ids=[...deferredCollections.current];deferredCollections.current.clear();for(const id of ids){const flight=flights.find(f=>f.id===id);if(flight)finishCollection(flight);}};
 const beginHold=()=>{if(!g?.result||dealing||paused||readDone===g)return;resultHold.current=true;setHolding(true);};
 const chooseChip=(n:number,source:React.RefObject<View|null>)=>{if(rules||picker||target||!active||pendingWin||(g&&!g.result))return;if(!betting){stakeRef.current=0;setBetting(true);}const next=addStake(stakeRef.current,n,chips);if(next!==stakeRef.current){stakeRef.current=next;setStake(next);setSelectedChips(items=>[...(betting?items:[]),n]);launch(n,'bet',source,selectionIndex.current++);}};
 const dealtFrom=useRef<{game:typeof g}|null>(null);
 const deal=()=>{if(betting&&stake>=10&&stake<=chips&&!settings&&!rules&&!picker&&!target&&active&&dealtFrom.current?.game!==g){dealtFrom.current={game:g};generation.current++;setFlights([]);startRound(stakeRef.current);setBetting(false);}};
 const cardsVisible=!!g&&!betting&&!(g.result&&celebrated===g);const p=value(g?.player??[]);const enabled=g?.phase==='player'&&!paused&&!dealing;const hidden=g?.phase==='player';
 const doubleUsed=useRef<typeof g>(null);
 const double=()=>{if(!enabled||!canDouble||!g||doubleUsed.current===g)return;doubleUsed.current=g;setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());doubleDown();};
 const repeat=()=>{if(!repeatBet||repeatBet>chips||pendingWin||rules||settings||picker||target||!active||(g&&!g.result))return;generation.current++;setFlights([]);stakeRef.current=repeatBet;setStake(repeatBet);setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());setBetting(true);};
 const send=(action:typeof hit)=>{if(enabled&&g)setGame(current=>current===g?action(g):current);};
 return <View ref={root} collapsable={false} onLayout={e=>setRootHeight(e.nativeEvent.layout.height)} style={{flex:1,backgroundColor:C.background,overflow:'hidden'}}>
 <View style={{height:48,flexDirection:'row',alignItems:'center',paddingHorizontal:0,borderBottomWidth:1,borderBottomColor:C.line}}><Pressable accessibilityRole="button" accessibilityLabel={es?'Volver':'Back'} onPress={back} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Feather name="arrow-left" size={20} color={C.ivory}/></Pressable><View style={{flex:1,alignItems:'center'}}><Text style={{color:C.ivory,fontSize:16,letterSpacing:3,fontWeight:'600'}}>BLACKJACK</Text><Text style={{color:C.gold,fontSize:9,letterSpacing:1.5}}>SOCIAL CLUB · 3:2</Text></View><Pressable accessibilityRole="button" accessibilityLabel={es?'Ajustes':'Settings'} onPress={()=>setSettings(true)} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Feather name="more-vertical" size={20} color={C.gold}/></Pressable></View>
 <View testID="blackjack-table-surface" style={{flex:1,minHeight:0}}>
 <View testID="blackjack-table-background" pointerEvents="none" style={{position:'absolute',top:0,bottom:0,left:0,right:0}}><DominoTableBackground opponentHeight={heroHeight} gift={null} es={es} finished={!!g?.result}/></View>
 <ScrollView contentContainerStyle={{paddingHorizontal:14,paddingBottom:12,flexGrow:1}}>
 <View style={{flex:1,minHeight:compact?445:540,paddingBottom:compact?170:144,gap:compact?8:12,justifyContent:'flex-start'}}>
 {cardsVisible&&g?.result&&!dealing&&readDone!==g&&describeResult(g,es).natural&&<View testID="blackjack-natural-table-overlay" pointerEvents="none" style={{position:'absolute',right:18,bottom:compact?24:48,zIndex:20}}><NaturalCardAccent paused={paused} victory={g.result==='blackjack'}/></View>}
 <View pointerEvents="none" style={{position:'absolute',top:(heroHeight-15+usableHeight-48-94)/2-42.5,left:20,right:20,height:85,alignItems:'center'}}><TableStamp title="BLACKJACK" engraved/></View>
 <View testID="blackjack-hero" style={{height:heroHeight,flexDirection:'row',alignItems:'flex-end',paddingHorizontal:12,gap:6,marginHorizontal:-14}}>
 <View testID="blackjack-balance" style={{width:82,flexShrink:1,alignSelf:'flex-start',marginTop:14,gap:4}}><Text style={{color:C.goldLight,fontSize:12}}>{es?'Ganadas':'Won'} {wins??0}</Text><Text style={{color:C.ivory,fontSize:12}}>{es?'Perdidas':'Lost'} {losses??0}</Text></View>
 <Pressable testID="blackjack-dealer" accessibilityRole="button" accessibilityLabel={es?`Cambiar dealer: ${dealer.name}`:`Change dealer: ${dealer.name}`} onPress={()=>setPicker(true)} style={{flex:1,minWidth:44,height:heroHeight}}><Image testID="blackjack-dealer-figure" source={dealer.image} resizeMode="contain" style={{position:'absolute',width:'100%',height:dealerFigureHeight,top:dealerFigureTop}}/></Pressable>
 <View style={{width:82,alignSelf:'flex-start',marginTop:14,gap:6}}><GameSwitchButton targetMode="poker" onSelect={()=>setTarget('poker')}/><GameSwitchButton whiteDomino targetMode="domino" onSelect={()=>setTarget('domino')}/></View></View>
 <View collapsable={false} style={{height:48,marginTop:compact?-20:-16,width:'100%',alignItems:'center',justifyContent:'center'}}><DealerChipRack rackRef={dealerBalance} testID="blackjack-dealer-pile" name={dealer.name} amount={dealerChips-(pendingWin&&dealerWon?payout*(1-(collected===g?1:launched.current===g?winProgress:0)):0)}/></View>
 <View style={{alignItems:'center',gap:6,marginTop:usableHeight<900?3:18}}>
 <View style={{position:'relative',width:Math.min((g?.dealer.length??0)*(cardWidth+6)-6,width-70),minWidth:cardWidth,alignItems:'center'}}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{maxWidth:'100%'}} contentContainerStyle={{gap:6}}>{cardsVisible&&g?.dealer.map((card,i)=><PlayingCard key={`${i}-${card.rank}${card.suit}`} card={hidden&&i===1?undefined:card} back={hidden&&i===1} width={cardWidth} delay={i<2?i*140:0} originX={80}/>)}</ScrollView>
 <View style={{position:'absolute',top:-5,right:-24}}>{cardsVisible&&!hidden&&g?<TotalBubble id="dealer-total">{String(value(g.dealer).total)}</TotalBubble>:<Text testID="dealer-total">{''}</Text>}</View></View></View>
 <View style={{flex:1,justifyContent:'flex-end',alignItems:'center',gap:7}}><View testID="blackjack-hand-message" style={{minHeight:compact?0:28,paddingVertical:compact?0:4,alignSelf:'stretch',paddingHorizontal:18}} /><View style={{position:'relative',width:Math.min((g?.player.length??0)*(cardWidth+6)-6,width-70),minWidth:cardWidth,alignItems:'center'}}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{maxWidth:'100%'}} contentContainerStyle={{gap:6}}>{cardsVisible&&g?.player.map((card,i)=><PlayingCard key={`${i}-${card.rank}${card.suit}`} card={card} width={cardWidth} delay={i<2?i*140:0} originX={80}/>)}</ScrollView>{cardsVisible&&g&&g.player.length>0?<View style={{position:'absolute',top:-5,right:-24}}><TotalBubble id="blackjack-player-total" color={p.bust?'#FFB9AF':'#FFF0D0'}>{p.total}{p.soft?(es?' · suave':' · soft'):''}</TotalBubble></View>:null}</View></View>
 </View>
 </ScrollView>
 <View testID="blackjack-lower-result" pointerEvents="box-none" style={{position:'absolute',left:enabled?116:12,right:enabled?116:12,bottom:0,height:g?.result&&describeResult(g,es,dealer.name).detail?64:44,justifyContent:'center',zIndex:24}}>{cardsVisible&&g?.result&&!dealing&&readDone!==g?<ResultBanner result={describeResult(g,es,dealer.name)} paused={paused||holding}/>:<TurnPrompt attention={active&&!rules&&!settings&&!picker&&!target&&(!!enabled||((betting||!g)&&chips>=10&&!pendingWin))} visible={active&&!rules&&!settings&&!picker&&!target} label={betting||!g?(stake>=10?(es?'Pulsa Deal':'Press Deal'):(es?'Elige tu apuesta':'Place Your Bet')):enabled?(es?'Tu turno':'Your Turn'):dealing?(es?'Repartiendo…':'Dealing…'):g.result?(collected!==g?(es?'Recogiendo…':'Collecting…'):''):g.phase==='dealer'?(es?'Turno del dealer':'Dealer’s Turn'):''}/>}</View>
 <View pointerEvents='box-none' style={{position:'absolute',left:0,right:0,bottom:0,height:64,zIndex:33}}><ResultHoldButton visible={cardsVisible&&!!g?.result&&!dealing&&readDone!==g} presentationKey={g?.result?g:null} id="blackjack-result-hold" holding={holding} disabled={paused} onHold={beginHold} onRelease={releaseHold} es={es}/></View>
 <View style={{position:'absolute',bottom:compact?28:17,left:(width-110)/2,width:110,alignItems:'center',gap:0,zIndex:12}}><View ref={pot} collapsable={false} testID="blackjack-bet-spot" style={{height:74,width:110,alignItems:'center',justifyContent:'center'}}><BetWell/><View style={{height:58,width:104,marginTop:12}}>{(visibleStake>0&&!flights.some(f=>f.kind==='win')?betSequence:[]).map((amount,i)=>({amount,i})).filter(({i})=>!betting||!ordered||landed.has(i)).map(({amount,i})=><View key={i} style={{position:'absolute',zIndex:i+1,left:i%3===2?29:3+(i%3)*52,bottom:Math.floor(i/3)*betLayerStep+(i%3===2?12:0),transform:[{scale:BANKROLL_CHIP_SCALE}],transformOrigin:'bottom left'}}><DenominationChip amount={amount} facingPlayer/></View>)}</View><View style={{position:'absolute',top:-17,alignSelf:'center'}}><TotalBubble id="blackjack-bet-total" down>{'$'+visibleStake.toLocaleString()}</TotalBubble></View></View><Pressable accessibilityRole="button" disabled={!(!g||!!g.result)||pendingWin||rules||picker||!!target||!active} onPress={()=>{if(!g||g.result){generation.current++;stakeRef.current=0;setStake(0);setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());setBetting(true);setFlights(f=>f.filter(x=>x.kind!=='bet'));}}} style={{paddingHorizontal:8,paddingTop:4,paddingBottom:12,opacity:(!g||!!g.result)&&!pendingWin?1:0}}><Text style={{color:C.muted,fontSize:12,transform:[{translateY:-8}]}}>{es?'Limpiar':'Clear'}</Text></Pressable></View>
 </View>

 <View onLayout={e=>setFooterHeight(e.nativeEvent.layout.height)} style={{paddingHorizontal:12,paddingTop:2,paddingBottom:10,minHeight:87,backgroundColor:'#704329'}}>
 <View pointerEvents="none" style={{position:'absolute',top:0,bottom:0,left:0,right:0}}><Svg width="100%" height="100%" viewBox="0 0 400 100" preserveAspectRatio="none"><Defs><LinearGradient id="bjWood" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#4D2C1C"/><Stop offset="0.4" stopColor="#865335"/><Stop offset="1" stopColor="#603922"/></LinearGradient><LinearGradient id="bjLipShadow" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#080F0B" stopOpacity="0.8"/><Stop offset="1" stopColor="#080F0B" stopOpacity="0"/></LinearGradient></Defs><Rect width="400" height="100" fill="url(#bjWood)"/>{[33,48,66,82,94].map((y,i)=><Path key={y} d={`M0 ${y} Q100 ${y-4} 210 ${y+1} T400 ${y-2}`} fill="none" stroke={i%2?'#B88352':'#321B11'} strokeOpacity="0.19" strokeWidth="1"/>)}<Path d="M0 0 H400 V7 Q200 22 0 7 Z" fill="#0C271C"/><Path d="M0 7 Q200 22 400 7 L400 28 Q200 40 0 28 Z" fill="url(#bjLipShadow)"/><Path d="M0 7 Q200 22 400 7" fill="none" stroke="#AF9362" strokeOpacity="0.38" strokeWidth="1.2"/></Svg></View>
 {chips<10&&(!g||g.result)&&!pendingWin?<Button id="blackjack-refill" label={es?'Agregar 1,000 fichas':'Add 1,000 chips'} onPress={()=>{refill();stakeRef.current=0;setStake(0);setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());setBetting(true);}}/>:null}
 <View ref={balance} collapsable={false} testID="blackjack-player-balance" style={{height:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:6}}><Text numberOfLines={1} style={{color:C.ivory,fontSize:11,maxWidth:130}}>{playerName}</Text><Text style={{color:C.goldLight,fontSize:13,fontWeight:'700'}}>{'$'+visibleChips.toLocaleString()}</Text></View>
 <BettingTray available={visibleChips} stake={visibleStake} balance={chips} es={es} canBet={(!g||!!g.result)&&!pendingWin&&!rules&&!picker&&!target&&active} onChip={chooseChip} onClear={()=>{if(!g||g.result){generation.current++;stakeRef.current=0;setStake(0);setSelectedChips([]);selectionIndex.current=0;setLanded(new Set());setBetting(true);setFlights(f=>f.filter(x=>x.kind!=='bet'));}}}/>
 </View>

 <FloatingAction id="blackjack-deal" label="DEAL" side="left" bottom={footerHeight+6} visible={betting&&stake>=10&&stake<=chips&&!rules&&!picker&&active&&!target} enabled onPress={deal}/>
 <FloatingAction id="blackjack-hit" label="HIT" side="right" bottom={footerHeight+64} visible={!!enabled} enabled={!!enabled} onPress={()=>send(hit)}/>
 <FloatingAction id="blackjack-stand" label="STAND" side="right" bottom={footerHeight+6} visible={!!enabled} enabled={!!enabled} onPress={()=>send(stand)}/>
 <FloatingAction id="blackjack-double" label={es?'DOBLAR':'DOUBLE'} side="left" bottom={footerHeight+6} visible={!!enabled&&!!canDouble} enabled={!!enabled&&!!canDouble} onPress={double}/>
 <FloatingAction id="blackjack-repeat" label={es?'REPETIR':'REPEAT BET'} side="left" bottom={footerHeight+6} visible={!!repeatBet&&!(betting&&stake>=10&&stake<=chips)&&(!g||!!g.result)&&!pendingWin&&!rules&&!settings&&!picker&&!target&&active} enabled onPress={repeat}/>
 {flights.map(f=><ChipFlight key={f.id} flight={f} sound={ready&&tileSound&&!f.silent} paused={settings||rules||picker||!!target||!active||holding} onProgress={f.kind==='win'?p=>{if(resultHold.current||f.generation!==generation.current||winDone.current.has(f.id))return;winProgresses.current.set(f.id,p);updateWinProgress();}:undefined} onComplete={()=>finishCollection(f)}/>)}
 <Modal visible={picker} transparent animationType="fade" onRequestClose={()=>setPicker(false)}><View style={{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(2,12,10,.84)'}}><View style={{padding:20,gap:16,backgroundColor:C.surface,borderRadius:22}}><Text style={{color:C.goldLight,fontSize:22}}>{es?'Elige tu dealer':'Choose your dealer'}</Text><DealerChoices selected={dealer.id} onSelect={id=>{setDealerId(id);setPicker(false);}}/><Button label={es?'Cerrar':'Close'} onPress={()=>setPicker(false)}/></View></View></Modal>
 <Modal visible={rules} transparent animationType="fade" onRequestClose={()=>setRules(false)}><View style={{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'center',padding:24}}><View style={{backgroundColor:C.surface,padding:22,borderRadius:18,gap:16,maxHeight:'90%'}}><Text style={{color:C.goldLight,fontSize:20}}>{es?'Reglas de Blackjack':'Blackjack rules'}</Text><ScrollView style={{flexShrink:1}}><Text style={{color:C.ivory,lineHeight:23}}>{es?'Acércate a 21 sin pasarte. J/Q/K valen 10; el as vale 1 u 11. As y carta de valor 10 en las dos primeras cartas forman blackjack natural y ganan salvo otro natural (empate). Pedir añade una carta; plantarse inicia el turno del dealer. El dealer pide hasta 16 y se planta en todo 17, incluido el suave. Si te pasas, pierdes aunque el dealer pudiera pasarse. Totales iguales empatan. Una baraja nueva por ronda. Fichas virtuales: victoria paga 1:1 y blackjack natural 3:2. Doblar en la primera decisión duplica la apuesta, da una carta y planta la mano. Repetir prepara la apuesta inicial anterior sin repartir; Deal inicia la ronda. Sin dividir ni seguro.':'Reach 21 without going over. J/Q/K count 10; an ace counts 1 or 11. An ace and a ten-value card in the initial two cards are a natural blackjack, winning unless the dealer also has a natural (push). Hit adds a card; stand starts the dealer turn. The dealer hits through 16 and stands on all 17, including soft 17. Player bust loses immediately. Equal totals push. Fresh single deck each round. Virtual chips: wins pay 1:1 and natural blackjack 3:2. Double on the first decision doubles the wager, draws one card and stands. Repeat bet prepares the previous initial wager without dealing; Deal starts the round. No splitting or insurance.'}</Text></ScrollView><Button id="blackjack-close-rules" label={es?'Cerrar':'Close'} onPress={()=>setRules(false)}/></View></View></Modal>
 <Modal visible={!!target} transparent animationType="fade" onRequestClose={()=>setTarget(null)}><View style={{flex:1,backgroundColor:'rgba(2,12,10,.84)',justifyContent:'center',padding:26}}><View accessibilityViewIsModal style={{backgroundColor:C.surface,borderRadius:24,padding:24,borderWidth:1,borderColor:C.line,gap:18}}>
 <Text style={{color:C.ivory,fontSize:23,fontWeight:'600'}}>{es?`¿Quieres cambiar a ${target==='poker'?'póker':'dominó'}?`:`Switch to ${target==='poker'?'poker':'dominoes'}?`}</Text>
 <Text style={{color:C.muted,fontSize:15,lineHeight:23}}>{es?'Tu partida actual quedará pausada para continuar al volver.':'Your current game will pause so you can continue when you return.'}</Text>
 <View style={{flexDirection:'row',gap:12}}><Pressable accessibilityRole="button" onPress={()=>setTarget(null)} style={{flex:1,padding:15,borderRadius:12,backgroundColor:C.raised,alignItems:'center'}}><Text style={{color:C.ivory}}>{es?'Cancelar':'Cancel'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{if(target){enterMode(target);setTarget(null);go('computerGame');}}} style={{flex:1,padding:15,borderRadius:12,backgroundColor:C.gold,alignItems:'center'}}><Text style={{color:C.background,fontWeight:'700'}}>{es?'Cambiar':'Switch'}</Text></Pressable></View>
 </View></View></Modal>
 <TableSettings matching={false} visible={settings} es={es} onClose={()=>setSettings(false)} onRules={()=>{setSettings(false);setRules(true);}}/>
 </View>;
}
