import React,{useEffect,useRef,useState} from 'react';
import {Animated,AccessibilityInfo,Pressable,Text} from 'react-native';
export function FloatingAction({id,label,side,visible,enabled,onPress,bottom,color}:{id:string;label:string;side:'left'|'right';visible:boolean;enabled:boolean;onPress:()=>void;bottom:number;color?:string}){
 const v=useRef(new Animated.Value(0)).current;const [mounted,setMounted]=useState(visible);const [reduced,setReduced]=useState<boolean|null>(null);
 useEffect(()=>{let alive=true;AccessibilityInfo.isReduceMotionEnabled().then(x=>{if(alive)setReduced(x);}).catch(()=>{if(alive)setReduced(true);});return()=>{alive=false;};},[]);
 useEffect(()=>{if(reduced===null)return;if(visible)setMounted(true);let alive=true;if(reduced){v.setValue(visible?1:0);setMounted(visible);return;}const a=Animated.timing(v,{toValue:visible?1:0,duration:260,useNativeDriver:true});a.start(({finished})=>{if(alive&&finished&&!visible)setMounted(false);});return()=>{alive=false;a.stop();};},[visible,reduced,v]);
 if(!mounted)return null;
 return <Animated.View pointerEvents={visible?'auto':'none'} style={{position:'absolute',zIndex:15,bottom,[side]:0,opacity:v,transform:[{translateX:v.interpolate({inputRange:[0,1],outputRange:[side==='left'?-110:110,0]})}]}}><Pressable testID={id} accessibilityRole="button" accessibilityState={{disabled:!enabled||!visible}} disabled={!enabled||!visible} onPress={()=>{if(enabled&&visible)onPress();}} style={{minHeight:46,width:112,minWidth:112,paddingHorizontal:10,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'#E5CB91',borderTopLeftRadius:side==='right'?14:0,borderBottomLeftRadius:side==='right'?14:0,borderTopRightRadius:side==='left'?14:0,borderBottomRightRadius:side==='left'?14:0,backgroundColor:color??(label==='HIT'?'#267B58':label==='STAND'?'#A4453D':'#B18B44'),opacity:enabled?1:.45}}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.7} style={{color:'#FFF2D2',fontSize:14,fontWeight:'800',letterSpacing:1}}>{label}</Text></Pressable></Animated.View>;
}
