import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import React from 'react';import {create,act} from 'react-test-renderer';import ts from 'typescript';import {newRound} from './engine.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
async function setup(lang,game){const navigation=[];let created=0;const state={game,name:'Ana',dealerId:'yuni',setGame(v){state.game=v;},setName(v){state.name=v;},setDealerId(v){state.dealerId=v;}};
 const deps={'../poker/TableGameContext':{useTableGame:()=>({setPokerName(v){state.pokerName=v;}})},'../computer/ComputerGameContext':{useComputerGame:()=>({game:null})},react:React,'react-native':Object.fromEntries(['View','Text','Pressable','ScrollView','TextInput'].map(x=>[x,x])),'../nav/NavContext':{useNav:()=>({go:v=>navigation.push(v),back(){}})},'../i18n/I18nContext':{useI18n:()=>({lang})},'../computer/tableTheme':{TABLE:{}},'./dealers':{DEALERS:[{id:'mateo'}],DealerChoices:'DealerChoices'},'./ClassicPlayingCard':{ClassicPlayingCard:'PlayingCard'},'./BlackjackContext':{useBlackjack:()=>state},'./engine':{newRound(){created++;return newRound();}}};
 const m={exports:{}};const code=ts.transpileModule(readFileSync(new URL('./BlackjackLobby.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;new Function('require','module','exports',code)(id=>{if(!(id in deps))throw Error(id);return deps[id];},m,m.exports);
 let r;await act(()=>{r=create(React.createElement(m.exports.BlackjackLobby));});return {r,state,navigation,get created(){return created;},async close(){await act(()=>r.unmount());}};
}
for(const lang of ['en','es']){
 test(`lobby ${lang}: fresh start creates only Blackjack and navigates to its table`,async()=>{const h=await setup(lang,null);try{const label=lang==='es'?'Jugar Blackjack':'Play Blackjack';const b=h.r.root.findAllByType('Pressable').find(x=>x.findAllByType('Text').some(t=>t.props.children===label));await act(()=>b.props.onPress());assert.equal(h.created,0);assert.equal(h.state.game,null);assert.deepEqual(h.navigation,['blackjackTable']);}finally{await h.close();}});
 test(`lobby ${lang}: resume preserves exact round; profile edits use Blackjack state`,async()=>{const g=newRound();const h=await setup(lang,g);try{await act(()=>h.r.root.findByType('TextInput').props.onChangeText('Bea'));await act(()=>h.r.root.findByType('DealerChoices').props.onSelect('yoi'));const label=lang==='es'?'Continuar partida':'Continue game';await act(()=>h.r.root.findAllByType('Pressable').find(x=>x.findAllByType('Text').some(t=>t.props.children===label)).props.onPress());assert.equal(h.created,0);assert.equal(h.state.game,g);assert.equal(h.state.name,'Bea');assert.equal(h.state.pokerName,'Bea');assert.equal(h.state.dealerId,'yoi');assert.deepEqual(h.navigation,['blackjackTable']);}finally{await h.close();}});
}
