import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {act,create} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';import {describeResult,RESULT_READ_MS} from './resultPresentation.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
function load(file,deps){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>deps[id],m,m.exports);return m.exports;}
const g=(player,dealer,result)=>({player:player.map(rank=>({rank,suit:'h'})),dealer:dealer.map(rank=>({rank,suit:'d'})),result,phase:'complete',deck:[]});
test('decorative natural effect preserves dealer and push outcomes and existing reading time',()=>{assert.equal(RESULT_READ_MS,2000);for(const round of [g([14,10],[9,10],'blackjack'),g([9,10],[14,10],'dealer'),g([14,10],[14,10],'push')])assert.equal(describeResult(round,false).natural,true);assert.equal(describeResult(g([10,9],[10,8],'player'),false).natural,false);assert.equal(describeResult(g([9,10],[14,10],'dealer'),false).tone,'loss');assert.equal(describeResult(g([14,10],[14,10],'push'),false).tone,'push');});
test('decorative ace has finite1500ms arc, no card deal animation, static reduced motion and cancellation',async()=>{
 const jobs=[];const rn={View:'View',Animated:{View:'AnimatedView',Value:class{setValue(){}interpolate(config){return config;}},timing(v,config){const job={config,start(){},stop(){this.stopped=true;}};jobs.push(job);return job;}},Easing:{quad:x=>x,inOut:x=>x}};
 const {NaturalCardAccent}=load('./NaturalCardAccent.tsx',{react:React,'react-native':rn,'./ClassicPlayingCard':{ClassicPlayingCard:'Card'}});let r;await act(()=>{r=create(React.createElement(NaturalCardAccent,{paused:false,reduced:false}));});assert.equal(jobs.length,1);assert.equal(jobs[0].config.duration,1500);const moving=r.root.findByProps({testID:'blackjack-natural-card-accent'});assert.deepEqual(moving.props.style.transform[0].translateY.outputRange,[0,-35,-38,0,0]);assert.equal(moving.props.style.opacity.outputRange.at(-1),0);const card=r.root.findByType('Card');assert.deepEqual(card.props.card,{rank:14,suit:'s'});assert.equal(card.props.animate,false);assert.equal(r.root.findByProps({testID:'blackjack-natural-card-accent'}).props.pointerEvents,'none');
 await act(()=>r.update(React.createElement(NaturalCardAccent,{paused:true,reduced:false})));assert.equal(jobs[0].stopped,true);await act(()=>r.update(React.createElement(NaturalCardAccent,{paused:false,reduced:true})));assert.equal(jobs.length,1);const root=r.root.findByProps({testID:'blackjack-natural-card-accent'});assert.equal(root.props.style.transform[0].translateY,0);assert.equal(root.props.accessibilityElementsHidden,true);await act(()=>r.update(React.createElement(NaturalCardAccent,{paused:false,reduced:false})));assert.equal(jobs.length,2);await act(()=>r.unmount());assert.equal(jobs[1].stopped,true);
});
