import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import React from 'react';import {create,act} from 'react-test-renderer';import ts from 'typescript';import * as engine from './engine.ts';import * as session from './session.ts';import * as presentation from './presentation.ts';import * as resultPresentation from './resultPresentation.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
test('turn and bet prompts share lower result band without a second message above cards',async()=>{const h=await mount();try{await h.tick(700);const band=h.r.root.findByProps({testID:'blackjack-lower-result'});assert.equal(band.findByType('TurnPrompt').props.label,'Your Turn');assert.equal(band.findByType('TurnPrompt').props.attention,true);assert.equal(h.r.root.findByProps({testID:'blackjack-hand-message'}).findAllByType('TurnPrompt').length,0);await act(()=>h.r.root.findByProps({testID:'blackjack-stand'}).props.onPress());await h.render();assert.equal(band.findByType('TurnPrompt').props.label,'Dealing…');assert.equal(band.findByType('TurnPrompt').props.attention,false);await h.tick(700);assert.equal(band.findByType('TurnPrompt').props.label,'Dealer’s Turn');assert.equal(band.findByType('TurnPrompt').props.attention,false);}finally{await h.close();}const empty=await mount('en',null);try{assert.equal(empty.r.root.findByProps({testID:'blackjack-lower-result'}).findByType('TurnPrompt').props.label,'Place Your Bet');const band=empty.r.root.findByProps({testID:'blackjack-lower-result'});assert.equal(band.props.style.left,band.props.style.right);assert.equal(band.findByType('TurnPrompt').props.attention,true);await act(()=>empty.r.root.findByType('BettingTray').props.onChip(20,{current:null}));await empty.render();assert.equal(band.props.style.left,band.props.style.right);assert.equal(band.findByType('TurnPrompt').props.label,'Press Deal');await empty.app('background');assert.equal(band.findByType('TurnPrompt').props.attention,false);assert.equal(band.findByType('TurnPrompt').props.visible,false);}finally{await empty.close();}});
test('automatic hand starts once at 2000 only after collection, cancels under pause and keeps lower winner',async()=>{const h=await mount('en',engine.newRound([c(14),c(9),c(10),c(8)]),true);try{await h.tick(700);assert.equal(h.r.root.findByType('ResultBanner').props.winner,undefined);const band=h.r.root.findByProps({testID:'blackjack-lower-result'});assert.equal(band.props.style.height,44);assert.equal(band.props.style.position,'absolute');assert.equal(band.findAllByType('PlayingCard').length,0);await act(()=>h.r.root.findByType('ChipFlight').props.onComplete());await h.render();await h.tick(1999);assert.deepEqual(h.starts,[]);await h.app('background');await h.tick();assert.deepEqual(h.starts,[]);await h.app('active');await h.tick(1999);assert.deepEqual(h.starts,[]);await h.tick(1);assert.deepEqual(h.starts,[20]);assert.equal(h.game.phase,'player');await h.render();assert.deepEqual(h.starts,[20]);}finally{await h.close();}});
function load(file,deps){const m={exports:{}};const code=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;new Function('require','module','exports',code)(id=>{if(!(id in deps))throw Error(id);return deps[id];},m,m.exports);return m.exports;}
const c=(rank,suit='s')=>({rank,suit});
test('player total bubble stays absent before cards and shows the actual dealt total',async()=>{
 const empty=await mount('en',null);try{assert.equal(empty.r.root.findAllByType('Text').some(t=>t.props.children==='—'),false);assert.equal(empty.r.root.findAllByProps({testID:'blackjack-player-total'}).length,0);}finally{await empty.close();}
 const dealt=await mount();try{assert.equal(dealt.r.root.findByProps({testID:'blackjack-player-total'}).props.children[0],engine.value(dealt.game.player).total);}finally{await dealt.close();}
});
async function mount(lang='en',initial=engine.newRound([c(10),c(9),c(8),c(7),c(10,'h')]),automatic=false,balanceAmount=1000){
 const navigation=[];const modes=[];const starts=[];let appListener;let backListener;let game=initial;let celebrated=null;let collected=null;const timers=new Map();let id=0;const oldSet=globalThis.setTimeout,oldClear=globalThis.clearTimeout;
 globalThis.setTimeout=(fn,ms)=>{timers.set(++id,{fn,ms});return id;};globalThis.clearTimeout=n=>timers.delete(n);
 const rn={View:'View',Text:'Text',Pressable:'Pressable',ScrollView:'ScrollView',Modal:'Modal',Image:'Image',AppState:{currentState:'active',addEventListener:(_event,fn)=>{appListener=fn;return {remove(){}};}},BackHandler:{addEventListener:(_event,fn)=>{backListener=fn;return {remove(){}};}},useWindowDimensions:()=>({width:320,height:568})};
 const deps={'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},'./TableFinish':{TableStamp:'TableStamp'},'../computer/ComputerGameContext':{useComputerGame:()=>({game:null})},'./SeatChipPile':{SeatChipPile:'SeatChipPile'},'./TiltSurface':{TiltSurface:'TiltSurface'},'react-native-svg':{__esModule:true,default:'Svg',Defs:'Defs',LinearGradient:'LinearGradient',Stop:'Stop',Rect:'Rect',Path:'Path',Text:'SvgText'},'@expo/vector-icons':{Feather:'Feather'},'../computer/DominoTableBackground':{DominoTableBackground:()=>null},'./dealers':{DEALERS:[{id:'mateo',name:'Mateo',image:1}],DealerChoices:'DealerChoices'},'../poker/CasinoChip':{ChipStack:()=>null},'./FloatingAction':{FloatingAction:({id,label,visible,enabled,onPress})=>visible?React.createElement('Pressable',{testID:id,disabled:!enabled,onPress},React.createElement('Text',null,label)):null},'./BetWell':{BetWell:'BetWell'},'./TurnPrompt':{TurnPrompt:'TurnPrompt'},'./ResultBanner':{ResultBanner:'ResultBanner'},'./NaturalCardAccent':{NaturalCardAccent:'NaturalCardAccent'},'./resultPresentation':resultPresentation,'./BettingTray':{BettingTray:'BettingTray',DenominationChip:'DenominationChip'},'./ChipFlight':{ChipFlight:'ChipFlight'},'./presentation':presentation,'./useBlackjackCardSound':{useBlackjackCardSound(){}},'../state/PrefsContext':{usePrefs:()=>({ready:false,tileSound:false})},react:React,'react-native':rn,'./engine':engine,'./BlackjackContext':{useBlackjack:()=>({game,setGame:fn=>{game=typeof fn==='function'?fn(game):fn;},collected,setCollected:v=>{collected=v;},celebrated,setCelebrated:v=>{celebrated=v;},autoStart:()=>{if(automatic){starts.push(20);game=engine.newRound([c(5),c(10),c(5),c(8),c(2)]);}},chips:balanceAmount,bet:20,canDouble:!!game&&game.phase==='player'&&game.player.length===2, doubleDown:()=>{const drawn=engine.hit(game);game=drawn.phase==='player'?engine.stand(drawn):drawn;},repeatBet:game?.result&&balanceAmount>=20?20:0,wins:0,losses:0,pushes:0,startRound:amount=>{starts.push(amount);game=engine.newRound();},refill(){},setDealerId(){},name:'Ana',dealerId:'mateo'})},'../computer/opponents':{OPPONENTS:[{id:'yuni',name:'Yuni',image:1}]},'../computer/TableSettings':{TableSettings:'TableSettings'},'../sound/useTableMusic':{useTableMusic(){}},'../computer/tableTheme':{TABLE:{}} ,'./ClassicPlayingCard':{ClassicPlayingCard:'PlayingCard'},'../i18n/I18nContext':{useI18n:()=>({lang})},'../nav/NavContext':{useNav:()=>({back(){navigation.push('back');},go(route){navigation.push(route);}})},'../poker/TableGameContext':{GameSwitchButton:({targetMode,onSelect})=>React.createElement('Pressable',{onPress:onSelect},React.createElement('Text',null,targetMode==='poker'?'Poker':'Domino')),useTableGame:()=>({enterMode(mode){modes.push(mode);}})}};
 const {BlackjackScreen}=load('./BlackjackScreen.tsx',deps);let r;await act(()=>{r=create(React.createElement(BlackjackScreen));});
 return {r,navigation,modes,starts,get pendingTimers(){return timers.size;},async app(state){await act(()=>appListener(state));},async hardwareBack(){await act(()=>backListener());},get game(){return game;},async render(){await act(()=>r.update(React.createElement(BlackjackScreen)));},async remount(){await act(()=>r.unmount());await act(()=>{r=create(React.createElement(BlackjackScreen));});this.r=r;},async tick(ms=Infinity){const jobs=[];for(const [key,job] of timers){if(job.ms<=ms){jobs.push(job.fn);timers.delete(key);}else job.ms-=ms;}await act(()=>jobs.forEach(fn=>fn()));await this.render();},async close(){await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}};
}
test('actual screen hides dealer hole and total; dealing locks Hit, then bust reveals and ends',async()=>{
 const h=await mount();try{
 const hit=()=>h.r.root.findByProps({testID:'blackjack-hit'});
 assert.equal(h.r.root.findAllByProps({testID:'blackjack-hit'}).length,0);assert.equal(h.r.root.findAllByType('PlayingCard').filter(x=>x.props.back).length,1);
 assert.equal(h.r.root.findByProps({testID:'dealer-total'}).props.children,'');
 await h.tick();assert.equal(hit().props.disabled,false);await act(()=>hit().props.onPress());await h.render();
 assert.equal(h.game.result,'dealer');assert.equal(h.r.root.findAllByType('PlayingCard').filter(x=>x.props.back).length,0);
 assert.equal(h.r.root.findAllByProps({testID:'blackjack-deal'}).length,0);
 }finally{await h.close();}
});
test('stand triggers automatic dealer and rules pause that timer; Spanish actions supported',async()=>{
 const h=await mount('es');try{await h.tick();await act(()=>h.r.root.findByProps({testID:'blackjack-stand'}).props.onPress());await h.render();assert.equal(h.game.phase,'dealer');
 await openRules(h);await h.render();await h.tick();assert.equal(h.game.phase,'dealer');
 await act(()=>h.r.root.findByProps({testID:'blackjack-close-rules'}).props.onPress());await h.render();await h.tick();await h.tick();assert.equal(h.game.result,'player');
 }finally{await h.close();}
});
test('provider preserves its round on screen unmount, separate from Poker state',async()=>{
 const m=load('./BlackjackContext.tsx',{react:React,'./session':session});let state;function Probe(){state=m.useBlackjack();return null;}let r;
 await act(()=>{r=create(React.createElement(m.BlackjackProvider,null,React.createElement(Probe)));});
 const g=engine.newRound();await act(()=>state.setGame(g));await act(()=>r.update(React.createElement(m.BlackjackProvider,null,null)));await act(()=>r.update(React.createElement(m.BlackjackProvider,null,React.createElement(Probe))));assert.equal(state.game,g);await act(()=>r.unmount());
});

test('natural immediately reveals dealer and Next round creates a fresh playable deal',async()=>{
 const h=await mount('en',engine.newRound([c(14),c(9),c(13),c(7)]));try{
 assert.equal(h.r.root.findAllByType('PlayingCard').filter(x=>x.props.back).length,0);
 await h.tick();await h.tick();const flight=h.r.root.findByType('ChipFlight');await act(()=>flight.props.onComplete());await h.render();assert.equal(h.r.root.findAllByProps({testID:'blackjack-deal'}).length,0);
 const tray=h.r.root.findByType('BettingTray');await act(()=>tray.props.onChip(20,{current:null}));await h.render();await act(()=>h.r.root.findByProps({testID:'blackjack-deal'}).props.onPress());await h.render();assert.equal(h.game.player.length,2);assert.equal(h.game.deck.length,48);
 }finally{await h.close();}
});

test('compact action controls stay outside the table scroll area',async()=>{
 const h=await mount();try{await h.tick();let node=h.r.root.findByProps({testID:'blackjack-hit'});while(node){assert.notEqual(node.type,'ScrollView');node=node.parent;}}finally{await h.close();}
});
test('inactive app pauses dealer; reactivation resumes exactly one legal step',async()=>{
 const h=await mount();try{await h.tick();await act(()=>h.r.root.findByProps({testID:'blackjack-stand'}).props.onPress());await h.render();await h.tick();await h.app('background');await h.tick();assert.equal(h.game.phase,'dealer');await h.app('active');await h.tick();assert.equal(h.game.result,'player');}finally{await h.close();}
});
test('switch cancellation preserves round; confirmation changes mode and routes without resetting',async()=>{
 const h=await mount();const button=label=>h.r.root.findAllByType('Pressable').find(x=>x.findAllByType('Text').some(t=>t.props.children===label));
 try{await h.tick();const before=h.game;await act(()=>button('Poker').props.onPress());await act(()=>button('Cancel').props.onPress());assert.equal(h.game,before);assert.deepEqual(h.navigation,[]);await act(()=>button('Poker').props.onPress());await act(()=>button('Switch').props.onPress());assert.deepEqual(h.modes,['poker']);assert.deepEqual(h.navigation,['computerGame']);assert.equal(h.game,before);}finally{await h.close();}
});
test('hardware Back dismisses rules before navigating and keeps round',async()=>{
 const h=await mount();try{const before=h.game;await openRules(h);await h.hardwareBack();assert.deepEqual(h.navigation,[]);await h.hardwareBack();assert.deepEqual(h.navigation,['back']);assert.equal(h.game,before);}finally{await h.close();}
});

test('multiple chip taps in the same event accumulate; clear removes wager flights without touching round',async()=>{
 const h=await mount('en',null);try{const tray=()=>h.r.root.findByType('BettingTray');await act(()=>{tray().props.onChip(20,{current:null});tray().props.onChip(50,{current:null});});await h.render();assert.equal(tray().props.stake,70);assert.equal(h.game,null);assert.deepEqual(h.r.root.findAllByType('DenominationChip').map(c=>c.props.amount),[20,50]);assert.equal(h.r.root.findByProps({testID:'blackjack-bet-total'}).props.children,'$70');assert.equal(h.r.root.findAllByType('ChipFlight').length,2);await act(()=>tray().props.onClear());assert.equal(tray().props.stake,0);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);}finally{await h.close();}
});
test('winning counter progresses visually and completion does not alter settled game',async()=>{
 const g=engine.newRound([c(14),c(9),c(13),c(7)]);const h=await mount('en',g);try{await h.tick();await h.tick();const f=h.r.root.findByType('ChipFlight');assert.equal(f.props.flight.kind,'win');const counter=()=>h.r.root.findByProps({testID:'blackjack-player-pile'}).props.amount.toLocaleString();assert.equal(counter(),'950');await act(()=>f.props.onProgress(.5));assert.equal(counter(),'975');await act(()=>f.props.onComplete());await h.render();assert.equal(counter(),'1,000');assert.equal(h.r.root.findByType('BettingTray').props.stake,0);assert.equal(h.r.root.findByProps({testID:'blackjack-bet-spot'}).findByType('Text').props.children,'$0');assert.equal(h.game,g);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);}finally{await h.close();}
});

test('only legal side actions appear while chip tray stays visible',async()=>{const h=await mount();try{const count=id=>h.r.root.findAllByProps({testID:id}).length;assert.equal(count('blackjack-hit'),0);assert.equal(count('blackjack-stand'),0);assert.equal(count('blackjack-deal'),0);await h.tick();assert.equal(count('blackjack-hit'),1);assert.equal(count('blackjack-stand'),1);await act(()=>h.r.root.findByProps({testID:'blackjack-hit'}).props.onPress());await h.render();assert.equal(count('blackjack-hit'),0);assert.equal(count('blackjack-stand'),0);assert.equal(h.r.root.findAllByType('BettingTray').length,1);}finally{await h.close();}});

test('flat table has no rotation gesture without changing round or stake',async()=>{const h=await mount();try{const before=h.game;assert.equal(h.r.root.findAllByProps({testID:'blackjack-tilt-up'}).length,0);const surface=h.r.root.findByProps({testID:'blackjack-table-surface'});assert.equal(surface.type,'View');assert.equal(surface.props.style.transform,undefined);assert.equal(surface.props.onMoveShouldSetResponder,undefined);assert.equal(h.game,before);assert.equal(h.r.root.findByType('BettingTray').props.stake,20);}finally{await h.close();}});

test('dealer win flies from BET to dealer pile and clears center only on collection',async()=>{const h=await mount();try{await h.tick();await act(()=>h.r.root.findByProps({testID:'blackjack-hit'}).props.onPress());await h.render();await h.tick();await h.tick();const flight=h.r.root.findByType('ChipFlight');assert.equal(flight.props.flight.kind,'win');assert.equal(flight.props.flight.amount,20);assert.equal(flight.props.flight.to.x,54);assert.equal(h.r.root.findByType('BettingTray').props.stake,20);await act(()=>flight.props.onComplete());await h.render();assert.equal(h.r.root.findByType('BettingTray').props.stake,0);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.equal(h.r.root.findAllByType('PlayingCard').length,0);assert.equal(h.r.root.findByProps({testID:'blackjack-dealer-pile'}).props.name,'Mateo');}finally{await h.close();}});
test('new wager hides old cards until Deal creates a fresh hand',async()=>{const h=await mount('en',engine.newRound([c(14),c(9),c(13),c(7)]));try{await h.tick();await h.tick();await act(()=>h.r.root.findByType('ChipFlight').props.onComplete());await h.render();assert.equal(h.r.root.findAllByType('PlayingCard').length,0);await act(()=>h.r.root.findByType('BettingTray').props.onChip(20,{current:null}));await h.render();assert.equal(h.r.root.findAllByType('PlayingCard').length,0);assert.equal(h.r.root.findAllByProps({testID:'blackjack-player-total'}).length,0);await act(()=>h.r.root.findByProps({testID:'blackjack-deal'}).props.onPress());await h.render();assert.equal(h.r.root.findAllByType('PlayingCard').length,4);}finally{await h.close();}});

async function openRules(h){
 await act(()=>h.r.root.findAllByType('Pressable').find(b=>['Settings','Ajustes'].includes(b.props.accessibilityLabel)).props.onPress());
 const settings=h.r.root.findByType('TableSettings');assert.equal(settings.props.visible,true);
 await act(()=>settings.props.onRules());assert.equal(h.r.root.findByType('TableSettings').props.visible,false);
}

test('collection begins with result while banner and cards last 2000ms, pauses safely and unlocks only after both',async()=>{const h=await mount('en',engine.newRound([c(9),c(14),c(10),c(13)]));try{
 await h.tick(700);const flight=h.r.root.findByType('ChipFlight');assert.equal(h.r.root.findByType('ResultBanner').props.result.title,'Mateo BLACKJACK');assert.equal(flight.props.flight.amount,20);assert.equal(flight.props.flight.to.x,54);
 await h.app('background');assert.equal(h.r.root.findByType('ChipFlight').props.paused,true);await h.tick();assert.equal(h.r.root.findAllByType('PlayingCard').length,4);await h.app('active');await h.tick(1999);assert.equal(h.r.root.findAllByType('ChipFlight').length,1);
 await act(()=>flight.props.onComplete());await h.render();assert.equal(h.r.root.findAllByType('PlayingCard').length,4);assert.equal(h.r.root.findAllByType('ResultBanner').length,1);assert.equal(h.r.root.findAllByProps({testID:'blackjack-repeat'}).length,0);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);await h.tick(1);assert.equal(h.r.root.findAllByType('PlayingCard').length,0);assert.equal(h.r.root.findAllByProps({testID:'blackjack-repeat'}).length,1);
 }finally{await h.close();}});
test('leaving during result hold cancels collection without changing settled round',async()=>{
 const g=engine.newRound([c(14),c(9),c(13),c(7)]);const h=await mount('en',g);await h.tick(700);assert.equal(h.pendingTimers,1);await h.close();assert.equal(h.pendingTimers,0);assert.equal(h.game,g);
});

test('natural decorative card rises on table in a separate layer outside readable result banner',async()=>{const h=await mount('en',engine.newRound([c(14),c(9),c(13),c(7)]));try{await h.tick(700);const accent=h.r.root.findByType('NaturalCardAccent');assert.equal(accent.props.victory,true);const layer=accent.parent;assert.equal(layer.props.testID,'blackjack-natural-table-overlay');assert.equal(layer.props.pointerEvents,'none');assert.equal(layer.props.style.position,'absolute');assert.equal(layer.props.style.bottom,24);assert.equal(layer.props.style.top,undefined);assert.equal(layer.findAllByType('ResultBanner').length,0);assert.equal(h.r.root.findAllByType('PlayingCard').length,4);assert.equal(h.r.root.findAllByType('ChipFlight').length,1);}finally{await h.close();}});

test('selecting a bet starts chip flight while betting, pauses only for interruptions and clear removes it',async()=>{const h=await mount('en',null);try{await act(()=>h.r.root.findByType('BettingTray').props.onChip(20,{current:null}));await h.render();const flight=()=>h.r.root.findByType('ChipFlight');assert.equal(flight().props.paused,false);assert.equal(flight().props.flight.kind,'bet');assert.equal(h.r.root.findByType('BettingTray').props.stake,20);await act(()=>h.r.root.findAllByType('Pressable').find(b=>b.props.accessibilityLabel==='Settings').props.onPress());assert.equal(flight().props.paused,true);await act(()=>h.r.root.findByType('TableSettings').props.onClose());assert.equal(flight().props.paused,false);await h.app('background');assert.equal(flight().props.paused,true);await h.app('active');assert.equal(flight().props.paused,false);await act(()=>flight().props.onComplete());assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.equal(h.r.root.findByType('BettingTray').props.stake,20);assert.equal(h.game,null);await act(()=>h.r.root.findByType('BettingTray').props.onChip(20,{current:null}));await act(()=>h.r.root.findByType('BettingTray').props.onClear());assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.equal(h.r.root.findByType('BettingTray').props.stake,0);}finally{await h.close();}});

test('Hit and Stand share the right edge with Hit above Stand and clear touch separation',async()=>{const h=await mount();try{await h.tick(700);const hit=h.r.root.findByProps({id:'blackjack-hit'}).props,stand=h.r.root.findByProps({id:'blackjack-stand'}).props;assert.equal(hit.side,'right');assert.equal(stand.side,'right');assert.equal(hit.bottom-stand.bottom,58);assert.equal(hit.enabled,true);assert.equal(stand.enabled,true);}finally{await h.close();}});

test('Double appears only at first decision and draws one; Repeat prepares wager then Deal replaces it in the same slot',async()=>{const h=await mount();try{assert.equal(h.r.root.findAllByProps({testID:'blackjack-double'}).length,0);await h.tick(700);const d=h.r.root.findByProps({testID:'blackjack-double'});await act(()=>d.props.onPress());await h.render();assert.equal(h.game.player.length,3);assert.equal(h.r.root.findAllByProps({testID:'blackjack-double'}).length,0);await h.tick(700);await h.tick(2000);const f=h.r.root.findByType('ChipFlight');await act(()=>f.props.onComplete());await h.render();const before=h.game;const repeatProps=h.r.root.findByProps({id:'blackjack-repeat'}).props;const repeat=h.r.root.findByProps({testID:'blackjack-repeat'}).props.onPress;await act(()=>{repeat();repeat();});await h.render();assert.equal(h.game,before);assert.deepEqual(h.starts,[]);assert.equal(h.r.root.findByType('BettingTray').props.stake,20);assert.equal(h.r.root.findAllByProps({testID:'blackjack-deal'}).length,1);const dealProps=h.r.root.findByProps({id:'blackjack-deal'}).props;assert.equal(dealProps.bottom,repeatProps.bottom);assert.equal(dealProps.side,repeatProps.side);assert.equal(h.r.root.findAllByProps({testID:'blackjack-repeat'}).length,0);const deal=h.r.root.findByProps({testID:'blackjack-deal'}).props.onPress;await act(()=>{deal();deal();});await h.render();assert.deepEqual(h.starts,[20]);}finally{await h.close();}});
test('human win and push fly once to human while presentation waits for unfinished collection',async()=>{for(const [cards,amount] of [[[c(14),c(9),c(10),c(8)],50],[[c(14),c(14,'h'),c(10),c(10,'h')],20]]){const h=await mount('en',engine.newRound(cards));try{await h.tick(700);const f=h.r.root.findByType('ChipFlight');assert.equal(f.props.flight.amount,amount);assert.equal(f.props.flight.to.y,348);assert.equal(h.r.root.findByType('ResultBanner').props.result.tone,amount===20?'push':'win');await h.tick(2000);assert.equal(h.r.root.findAllByType('ResultBanner').length,0);assert.equal(h.r.root.findAllByType('PlayingCard').length,4);assert.equal(h.r.root.findAllByProps({testID:'blackjack-repeat'}).length,0);await h.tick();assert.equal(h.r.root.findAllByType('ChipFlight').length,1);await act(()=>{f.props.onComplete();f.props.onComplete();});await h.render();assert.equal(h.r.root.findAllByType('PlayingCard').length,0);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);}finally{await h.close();}}});
test('completed flight survives leaving before banner ends without flying or paying again on return',async()=>{const h=await mount('en',engine.newRound([c(14),c(9),c(10),c(8)]));try{await h.tick(700);await act(()=>h.r.root.findByType('ChipFlight').props.onComplete());await h.render();await h.remount();await h.tick(700);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.equal(h.r.root.findAllByType('ResultBanner').length,1);assert.equal(h.r.root.findAllByType('PlayingCard').length,4);await h.tick(2000);assert.equal(h.r.root.findAllByType('PlayingCard').length,0);}finally{await h.close();}});

test('late flight delays automatic deal after banner hides; insufficient balance returns to bets',async()=>{for(const balance of [1000,19]){const h=await mount('en',engine.newRound([c(9),c(14),c(10),c(10)]),true,balance);try{await h.tick(700);const flight=h.r.root.findByType('ChipFlight');await h.tick(1999);assert.equal(h.r.root.findAllByType('ResultBanner').length,1);await h.tick(1);assert.equal(h.r.root.findAllByType('ResultBanner').length,0);assert.deepEqual(h.starts,[]);assert.equal(h.r.root.findAllByType('PlayingCard').length,4);await h.app('background');await act(()=>flight.props.onComplete());await h.render();assert.deepEqual(h.starts,[]);await h.app('active');assert.deepEqual(h.starts,balance===19?[]:[20]);if(balance===19){assert.equal(h.r.root.findByType('BettingTray').props.canBet,true);assert.equal(h.r.root.findByType('BettingTray').props.stake,0);assert.equal(h.r.root.findAllByProps({testID:'blackjack-repeat'}).length,0);}}finally{await h.close();}}});

test('dealer figure follows Domino visible head and table height with original art',async()=>{const h=await mount();try{const hero=h.r.root.findByProps({testID:'blackjack-hero'});assert.equal(hero.props.style.height,105);assert.equal(hero.props.style.gap,6);assert.equal(hero.props.style.paddingHorizontal,12);const figure=h.r.root.findByProps({testID:'blackjack-dealer-figure'});assert.equal(figure.props.source,1);const content=120*1.28/1.5;assert.ok(Math.abs(figure.props.style.height*1328/1374-content*327/400)<.001);assert.ok(Math.abs(figure.props.style.top+figure.props.style.height*8/1374-(-105*.04+(105*1.1-content)/2+content*17/400))<.001);assert.equal(h.r.root.findByProps({testID:'blackjack-dealer'}).props.style.minWidth,44);}finally{await h.close();}});
