import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {create,act} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
test('skip first beat:3599ms static,3600ms single-beat loop; stable rerenders and initial wait cancellation',async()=>{
 const oldSet=setTimeout,oldClear=clearTimeout;let now=0,id=0;const timers=new Map();globalThis.setTimeout=(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);
 const jobs=[],values=[];let preference;let removed=0;const rn={AccessibilityInfo:{isReduceMotionEnabled:async()=>false,addEventListener:(_e,fn)=>{preference=fn;return{remove(){removed++;}};}},Animated:{Text:'AnimatedText',Value:class{constructor(v){this.value=v;values.push(this);}setValue(v){this.value=v;}},timing(_v,config){return{config};},delay(ms){return{delay:ms};},sequence(parts){return{parts};},loop(sequence){const a={sequence,started:false,stopped:false,start(){this.started=true;},stop(){this.stopped=true;}};jobs.push(a);return a;}}};
 const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('./PokerTurnPrompt.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>({react:React,'react-native':rn})[id],m,m.exports);let r;const render=async active=>act(()=>r?r.update(React.createElement(m.exports.PokerTurnPrompt,{active,label:'Your Turn'})):r=create(React.createElement(m.exports.PokerTurnPrompt,{active,label:'Your Turn'})));const tick=async ms=>{now+=ms;await act(()=>{for(const [key,t]of timers)if(t.at<=now){timers.delete(key);t.fn();}});};
 try{await render(false);assert.equal(jobs.length,0);assert.equal(r.root.findByType('AnimatedText').children.join(''),'Your Turn');await render(true);assert.equal(jobs.length,1);assert.equal(jobs[0].started,false);await tick(1000);await render(true);assert.equal(jobs.length,1,'ordinary rerender must not restart wait');await tick(2599);assert.equal(jobs[0].started,false);assert.equal(values[0].value,1);await tick(1);assert.equal(jobs[0].started,true);
 assert.deepEqual(jobs[0].sequence.parts.map(p=>p.config?.duration??p.delay),[210,210,3180]);assert.deepEqual(jobs[0].sequence.parts.filter(p=>p.config).map(p=>p.config.toValue),[1.07,1],'exactly one peak');assert.equal(jobs[0].sequence.parts.reduce((ms,p)=>ms+(p.config?.duration??p.delay),0),3600,'every native loop repeats single beat after3600ms without repeating initial wait');assert.equal(timers.size,0);assert.equal(r.root.findByType('AnimatedText').props.style.color,'#F5F0E4');await render(false);assert.equal(jobs[0].stopped,true);assert.equal(values[0].value,1);
 await render(true);await tick(1000);await render(false);await tick(5000);assert.equal(jobs[1].started,false,'act or pause before deadline produces no beat');assert.equal(timers.size,0);await render(true);await act(()=>preference(true));await tick(4000);assert.equal(jobs[2].started,false);assert.equal(jobs[2].stopped,true);assert.equal(values[0].value,1);await act(()=>preference(false));await tick(3599);assert.equal(jobs[3].started,false);await tick(1);assert.equal(jobs[3].started,true);await act(()=>r.unmount());r=null;assert.equal(jobs[3].stopped,true);assert.equal(removed,1);
 await render(true);await act(()=>r.unmount());r=null;await tick(4000);assert.equal(jobs[4].started,false,'exit during initial wait cancels native start');assert.equal(timers.size,0);assert.equal(removed,2);
 }finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}
});
