import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import React from 'react';import {create,act} from 'react-test-renderer';import ts from 'typescript';
import {describePokerResult} from './resultPresentation.ts';
import {payoutAwards} from './payoutPresentation.ts';import * as engine from './engine.ts';import * as rebuy from './rebuy.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const load=(file,deps)=>{const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>{if(id in deps)return deps[id];throw Error(id);},m,m.exports);return m.exports;};
const rn={View:'View',Text:'Text',Pressable:'Pressable',Modal:'Modal',Image:'Image',ScrollView:'ScrollView',AppState:{currentState:'active',addEventListener:()=>({remove(){}})},BackHandler:{addEventListener:()=>({remove(){}})},useWindowDimensions:()=>({width:390,height:844,fontScale:1})};
const base={'../computer/OpponentDrinkingAvatar':{OpponentDrinkingAvatar:'OpponentDrinkingAvatar'},'./PokerTurnPrompt':{PokerTurnPrompt:({label})=>React.createElement('Text',null,label)},react:React,'react-native':rn,'../computer/TableSettings':{TableSettings:'TableSettings'},'../sound/useTableMusic':{useTableMusic(){}},'../computer/tableTheme':{TABLE:{}} };
const {usePokerResultTransition}=load('./usePokerResultTransition.ts',{react:React,'./rebuy':rebuy});
const {PokerContinuation}=load('./PokerContinuation.tsx',{...base,'./rebuy':rebuy});
const finished=seat=>({...engine.newHand(undefined,()=>.3),street:'complete',result:{winner:seat==='human'?'computer':'human',reason:'fold',pot:2000},stacks:{human:seat==='human'?0:2000,computer:seat==='computer'?0:2000},bets:{human:0,computer:0},total:{human:0,computer:0}});
test('rebuy identifies the bankrupt human or rival in ES/EN and offers all three amounts',async()=>{
 for(const seat of ['human','computer'])for(const es of [true,false]){
  const names={human:'Juhni',computer:'Rigo'};let r;
  await act(()=>{r=create(React.createElement(PokerContinuation,{game:finished(seat),es,names,onContinue(){}}));});
  const texts=r.root.findByType('Modal').findAllByType('Text').map(t=>t.children.join(''));
  assert.deepEqual(texts,[es?'Comprar fichas':'Buy chips',es?`${names[seat]} se quedó sin fichas.`:`${names[seat]} ran out of chips.`,'500','750','1,000',es?'Cancelar':'Cancel',es?'Confirmar y continuar':'Confirm and continue',es?'Simulación; no es dinero real.':'Simulation only; no real money.']);
  for(const amount of [500,750,1000])assert.equal(r.root.findByProps({testID:`rebuy-${amount}`}).props.accessibilityLabel,`${amount} ${es?'fichas':'chips'}`);
  assert.ok(texts.includes('1,000'));await act(()=>r.unmount());
 }
});
test('actual PokerScreen: human zero opens Buy chips instead of Next hand/reset, credits only human',async()=>{
 let game=finished('human');let shown=`${game.hand}-${game.board.length}`;
 const {PokerScreen}=load('./PokerScreen.tsx',{...base,'./PokerResultBanner':{PokerResultBanner:({result,paused})=>React.createElement('PokerResultBanner',{result,paused},React.createElement('Text',null,result.title),React.createElement('Text',null,result.detail))},'./resultPresentation':{describePokerResult},'../blackjack/BlackjackContext':{useBlackjack:()=>({name:''})},'../blackjack/SeatChipPile':{SeatChipPile:'SeatChipPile'},'../blackjack/TiltSurface':{TiltSurface:'TiltSurface'},'../blackjack/TableFinish':{WoodSurface:()=>null,TableStamp:()=>null},'./payoutPresentation':{payoutAwards},'../blackjack/ChipFlight':{ChipFlight:'ChipFlight'},'./ChipRaiseTray':{ChipRaiseTray:'ChipRaiseTray',SelectedChipPile:'SelectedChipPile',RaiseControls:'RaiseControls'},'../blackjack/FloatingAction':{FloatingAction:'FloatingAction'},'./engine':engine,'./PokerContinuation':{PokerContinuation},'./rebuy':rebuy,'./usePokerResultTransition':{usePokerResultTransition:()=>false},'./winningHighlights':{winningHighlights:()=>[]},'./tableFit':{communityCardWidth:()=>50,pokerBoardZoneHeight:()=>255},'./PokerHandHint':{PokerHandHint:()=>null},'./PokerCard':{PokerCard:'PokerCard'},'./CardDealSound':{CardDealSound:()=>null},'./CasinoChip':{ChipStack:()=>null},'../computer/OpponentChoices':{OpponentChoices:()=>null},'../computer/DominoTableBackground':{DominoTableBackground:()=>null},'@expo/vector-icons':{Feather:()=>null},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:24,bottom:34})},'../computer/ComputerGameContext':{useComputerGame:()=>({opponentId:'rival',setOpponentId(){}})},'../computer/opponents':{OPPONENTS:[{id:'rival',name:'Rival'}]},'../i18n/I18nContext':{useI18n:()=>({lang:'en'})},'../nav/NavContext':{useNav:()=>({back(){}})},'../state/PrefsContext':{usePrefs:()=>({ready:false})},'../sound/useTableMusic':{useTableMusic(){}},'./TableGameContext':{GameSwitchButton:()=>null,useTableGame:()=>({poker:game,pokerCollected:game,setPokerCollected(){},pokerStartingChips:1000,pokerName:'You',pokerShown:shown,setPoker:v=>{game=typeof v==='function'?v(game):v;},setPokerShown:v=>{shown=v;}})}});
 let r;await act(()=>{r=create(React.createElement(PokerScreen));});
 const rivalRow=r.root.findByProps({testID:'poker-rival-cards'});assert.equal(rivalRow.props.style.top,15);assert.equal(rivalRow.props.style.gap,6);assert.equal(rivalRow.findAllByType('PokerCard').length,2);assert.ok(rivalRow.findAllByType('PokerCard').every(c=>c.props.width===68));assert.equal(r.root.findByProps({testID:'poker-rival-lane'}).props.style.height,95.5);const hero=r.root.findByProps({testID:'poker-hero'});assert.ok(Math.abs(hero.props.style.height-157.2)<.001);assert.equal(hero.props.style.gap,6);assert.equal(hero.props.style.paddingHorizontal,12);const avatar=r.root.findByType('OpponentDrinkingAvatar');assert.ok(Math.abs(avatar.props.height-157.2)<.001);assert.equal(avatar.props.gift,null);assert.equal(avatar.props.invitation,null);const background=r.root.findByProps({testID:'poker-table-background'});assert.equal(background.props.style.left,0);assert.equal(background.props.style.right,0);const surface=r.root.findByProps({testID:'poker-table-surface'});assert.equal(surface.type,'View');assert.equal(surface.props.style.transform,undefined);assert.equal(surface.props.onMoveShouldSetResponder,undefined);
 const tableScroll=surface.findByType('ScrollView');assert.equal(tableScroll.props.scrollEnabled,false,'dragging felt must not move cards or opponent');assert.equal(tableScroll.props.bounces,false);assert.equal(tableScroll.props.overScrollMode,'never');
 assert.notEqual(r.root.findAllByType('ScrollView').find(s=>s!==tableScroll).props.scrollEnabled,false,'rules and opponent picker remain scrollable');
 assert.ok((r.root.findAllByType('View')[0].props.style.marginBottom??0)>=0,'Poker must stay inside the parent bottom safe area');
 for(const host of r.root.findAll(n=>typeof n.type==='string'&&n.type!=='Text'))assert.equal(host.children.some(c=>typeof c==='string'),false,'raw text outside Text');
 const texts=r.root.findAllByType('Text').map(t=>t.children.join(''));
 assert.equal(texts.includes('Next hand'),false);assert.ok(texts.includes('Buy chips · Simulation'));
 assert.equal(r.root.findAllByType('Modal').filter(m=>m.props.visible).length,1);
 await act(()=>r.root.findByProps({testID:'rebuy-750'}).props.onPress());
 await act(()=>r.root.findByProps({testID:'rebuy-confirm'}).props.onPress());
 assert.equal(game.stacks.human+game.bets.human,750);assert.equal(game.stacks.computer+game.bets.computer,2000);
 await act(()=>r.unmount());
});
test('cancel/back preserve balances, rival rebuy is explicit, and dealing blocks modal',async()=>{
 const game=finished('computer');let received;let r;const props={game,es:true,names:{human:'You',computer:'Rival'},onContinue:n=>{received=n;}};
 await act(()=>{r=create(React.createElement(PokerContinuation,{...props,blocked:true}));});assert.equal(r.root.findByType('Modal').props.visible,false);
 await act(()=>r.update(React.createElement(PokerContinuation,props)));assert.equal(r.root.findByType('Modal').props.visible,true);
 await act(()=>r.root.findByProps({testID:'rebuy-cancel'}).props.onPress());assert.equal(received,undefined);assert.equal(r.root.findByType('Modal').props.visible,false);
 await act(()=>r.root.findByProps({testID:'poker-continue'}).props.onPress());
 await act(()=>r.root.findByType('Modal').props.onRequestClose());assert.equal(received,undefined);
 await act(()=>r.root.findByProps({testID:'poker-continue'}).props.onPress());
 await act(()=>r.root.findByProps({testID:'rebuy-confirm'}).props.onPress());assert.equal(received.stacks.computer+received.bets.computer,500);assert.equal(received.stacks.human+received.bets.human,2000);
 await act(()=>r.unmount());
});

test('PokerScreen collects immediately, shows one artistic result then auto advances once after2000ms',async()=>{
 for(const winner of ['human','computer','tie']){
 let game={...finished('human'),stacks:{human:900,computer:1100},result:{winner,reason:'fold',pot:100}};let collected=null,shown=`${game.hand}-${game.board.length}`,listener;
 const oldState=rn.AppState.currentState;rn.AppState.currentState='background';const initial=game,before=JSON.stringify(game),oldSet=setTimeout,oldClear=clearTimeout;let now=0,id=0,r;const jobs=new Map();
 globalThis.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>jobs.delete(id);
 const originalAdd=rn.AppState.addEventListener;rn.AppState.addEventListener=(_e,fn)=>{listener=fn;return{remove(){}};};
 const {PokerScreen}=load('./PokerScreen.tsx',{...base,'./PokerResultBanner':{PokerResultBanner:({result,paused})=>React.createElement('PokerResultBanner',{result,paused},React.createElement('Text',null,result.title),React.createElement('Text',null,result.detail))},'./resultPresentation':{describePokerResult},'../blackjack/BlackjackContext':{useBlackjack:()=>({name:''})},'../blackjack/SeatChipPile':{SeatChipPile:'SeatChipPile'},'../blackjack/TiltSurface':{TiltSurface:'TiltSurface'},'../blackjack/TableFinish':{WoodSurface:()=>null,TableStamp:()=>null},'./payoutPresentation':{payoutAwards},'../blackjack/ChipFlight':{ChipFlight:'ChipFlight'},'./ChipRaiseTray':{ChipRaiseTray:'ChipRaiseTray',SelectedChipPile:'SelectedChipPile',RaiseControls:'RaiseControls'},'../blackjack/FloatingAction':{FloatingAction:'FloatingAction'},'./engine':engine,'./PokerContinuation':{PokerContinuation},'./rebuy':rebuy,'./usePokerResultTransition':{usePokerResultTransition},'./winningHighlights':{winningHighlights:()=>[]},'./tableFit':{communityCardWidth:()=>50,pokerBoardZoneHeight:()=>255},'./PokerHandHint':{PokerHandHint:()=>null},'./PokerCard':{PokerCard:'PokerCard'},'./CardDealSound':{CardDealSound:()=>null},'./CasinoChip':{ChipStack:()=>null},'../computer/OpponentChoices':{OpponentChoices:()=>null},'../computer/DominoTableBackground':{DominoTableBackground:()=>null},'@expo/vector-icons':{Feather:()=>null},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:24,bottom:34})},'../computer/ComputerGameContext':{useComputerGame:()=>({opponentId:'rival',setOpponentId(){}})},'../computer/opponents':{OPPONENTS:[{id:'rival',name:'Rival'}]},'../i18n/I18nContext':{useI18n:()=>({lang:'en'})},'../nav/NavContext':{useNav:()=>({back(){}})},'../state/PrefsContext':{usePrefs:()=>({ready:false})},'../sound/useTableMusic':{useTableMusic(){}},'./TableGameContext':{GameSwitchButton:()=>null,useTableGame:()=>({poker:game,pokerCollected:collected,setPokerCollected:v=>{collected=v;},pokerStartingChips:1000,pokerName:'You',pokerShown:shown,setPoker:v=>{game=typeof v==='function'?v(game):v;},setPokerShown:v=>{shown=v;}})}});

 const render=async()=>act(()=>r?r.update(React.createElement(PokerScreen)):r=create(React.createElement(PokerScreen)));
 const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of jobs)if(j.at<=now){jobs.delete(key);j.fn();}});await render();};
 try{
  await render();const fold=r.root.findByProps({id:'poker-fold'}).props,check=r.root.findByProps({id:'poker-check-call'}).props,allIn=r.root.findByProps({id:'poker-all-in'}).props;assert.equal(fold.side,'right');assert.equal(check.side,'right');assert.equal(allIn.side,'left');assert.ok(check.bottom-fold.bottom>=58,'Check/Call above Fold with separate touch targets');assert.equal(allIn.bottom,fold.bottom);assert.equal(r.root.findByType('PokerResultBanner').props.result.tone,winner==='tie'?'push':winner==='human'?'win':'loss');
  const resultFooter=r.root.findByProps({testID:'poker-result-footer'});const strip=r.root.findByProps({testID:'poker-message-overlay'}),surface=r.root.findByProps({testID:'poker-table-surface'});assert.equal(strip.parent,surface,'messages overlay belongs to continuous felt');assert.equal(strip.props.style.position,'absolute');assert.equal(strip.props.style.bottom,0);assert.equal(strip.props.style.backgroundColor,undefined);assert.equal(strip.props.style.minHeight,64);assert.equal(resultFooter.parent,strip);assert.equal(resultFooter.props.style.position,undefined);assert.equal(resultFooter.props.pointerEvents,'none');
  const texts=r.root.findAllByType('Text').map(t=>t.children.join(''));assert.equal(texts.filter(t=>/YOU WIN|YOU LOSE|SPLIT POT| wins | WINS$|gana/i.test(t)).length,1,'only the banner announces the outcome');assert.equal(texts.filter(t=>t.includes('100')).length,1,'pot is described only in the banner');
  assert.equal(r.root.findAllByProps({testID:'poker-continue'}).length,0,'no Next hand over table');assert.equal(game,initial);
  await tick(3499);assert.equal(r.root.findAllByType('ChipFlight').length,0);
  await act(()=>listener('background'));await tick(5000);assert.equal(r.root.findAllByType('ChipFlight').length,0);
  await act(()=>listener('active'));await render();const flights=r.root.findAllByType('ChipFlight');const complete=flights.map(f=>f.props.onComplete);assert.equal(flights.length,winner==='tie'?2:1);
  assert.equal(JSON.stringify(game),before);assert.equal(collected,null);assert.equal(r.root.findAllByProps({testID:'poker-continue'}).length,0);
  await act(()=>listener('background'));await render();assert.equal(r.root.findAllByType('ChipFlight').every(f=>f.props.paused),true);await act(()=>listener('active'));await render();assert.equal(r.root.findAllByType('ChipFlight').length,flights.length);
  await act(()=>complete[0]());await render();
  if(winner==='tie'){assert.equal(collected,null);await act(()=>complete[0]());await render();assert.equal(collected,null,'duplicate completion must not finish a split pot');await act(()=>complete[1]());await render();}
  assert.equal(collected,game);assert.equal(JSON.stringify(game),before);assert.equal(r.root.findAllByType('PokerResultBanner').length,1);assert.equal(r.root.findAllByProps({testID:'poker-continue'}).length,0);
  await tick(1999);assert.equal(game,initial);await tick(1);assert.equal(game.hand,initial.hand+1);assert.equal(r.root.findAllByType('PokerResultBanner').length,0);assert.equal(r.root.findByProps({testID:'poker-message-overlay'}).findAllByType('Text').filter(t=>t.children.join('')==='Dealing…').length,1);assert.equal(r.root.findByProps({testID:'poker-fixed-table-content'}).findAllByType('Text').filter(t=>/Dealing|Your Turn|is thinking/.test(t.children.join(''))).length,0);assert.equal(game.stacks.human+game.bets.human,initial.stacks.human);assert.equal(game.stacks.computer+game.bets.computer,initial.stacks.computer);await tick(10000);assert.equal(game.hand,initial.hand+1);
 }finally{if(r)await act(()=>r.unmount());rn.AppState.currentState=oldState;rn.AppState.addEventListener=originalAdd;globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}
 }
});
