import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import React from 'react';import {create,act} from 'react-test-renderer';import ts from 'typescript';import * as engine from './engine.ts';import {payoutAwards} from './payoutPresentation.ts';import {chipAmounts} from '../blackjack/chipAmounts.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
async function mount(initial=engine.newHand(undefined,()=>.3,{human:1000,computer:5000}),measureNodes=false){
 let game=initial,shown='',switchTarget=null,collected=null;const jobs=new Map();let serial=0;const oldSet=setTimeout,oldClear=clearTimeout;
 globalThis.setTimeout=(fn,ms)=>{jobs.set(++serial,{fn,ms});return serial;};globalThis.clearTimeout=id=>jobs.delete(id);
 const rn={View:'View',Text:'Text',Pressable:'Pressable',ScrollView:'ScrollView',Modal:'Modal',useWindowDimensions:()=>({width:390,height:844,fontScale:1}),AppState:{currentState:'active',addEventListener:()=>({remove(){}})},BackHandler:{addEventListener:()=>({remove(){}})}};
 const source=readFileSync(new URL('./PokerScreen.tsx',import.meta.url),'utf8');const deps={react:React,'react-native':rn,'./engine':engine,'./payoutPresentation':{payoutAwards},'../blackjack/chipAmounts':{chipAmounts},'../blackjack/BettingTray':{BANKROLL_CHIP_SCALE:.92}};
 for(const match of source.matchAll(/import \{([^}]+)\} from '([^']+)'/g)){if(deps[match[2]])continue;deps[match[2]]=Object.fromEntries(match[1].split(',').map(s=>s.trim()).filter(s=>!s.startsWith('type ')).map(s=>[s,s]));}
 Object.assign(deps,{'../computer/tableTheme':{TABLE:{}},'../computer/opponents':{OPPONENTS:[{id:'test',name:'Rival'}]},'../i18n/I18nContext':{useI18n:()=>({lang:'en'})},'../nav/NavContext':{useNav:()=>({back(){}})},'../state/PrefsContext':{usePrefs:()=>({ready:false})},'../sound/useTableMusic':{useTableMusic(){}},'../blackjack/BlackjackContext':{useBlackjack:()=>({name:'Ana'})},'../computer/ComputerGameContext':{useComputerGame:()=>({opponentId:'test',setOpponentId(){}})},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},'./usePokerResultTransition':{usePokerResultTransition:()=>false},'./tableFit':{communityCardWidth:()=>40,pokerBoardZoneHeight:()=>140},'./winningHighlights':{winningHighlights:()=>[]},'./rebuy':{bankruptSeat:()=>null},'./TableGameContext':{GameSwitchButton:'GameSwitchButton',useTableGame:()=>({poker:game,pokerCollected:collected,setPokerCollected:v=>collected=v,pokerStartingChips:3000,pokerName:'Ana',pokerShown:shown,setPokerShown:v=>shown=v,setPoker:fn=>game=typeof fn==='function'?fn(game):fn,switchTarget})}});
 const m={exports:{}};new Function('require','module','exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>{if(!deps[id])throw Error(id);return deps[id];},m,m.exports);
 let r;const render=async()=>act(()=>r?r.update(React.createElement(m.exports.PokerScreen)):r=create(React.createElement(m.exports.PokerScreen),measureNodes?{createNodeMock:el=>({measureInWindow:cb=>el.props.testID==='poker-player-balance'?cb(12,760,366,20):el.props.testID==='poker-pot-spot'?cb(15,400,70,74):cb(0,0,390,844)})}:undefined));
 await render();shown=game?`${game.hand}-${game.board.length}`:'';await render();
 return {r,render,get game(){return game;},pile:()=>r.root.findByType('ChipRaiseTray').props.balance,tray:()=>r.root.findByType('ChipRaiseTray'),controls:()=>r.root.findByType('RaiseControls'),async setGame(g){game=g;shown=`${g.hand}-${g.board.length}`;await render();},async close(){await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}};
}
test('selection reserves each chip, Clear restores, confirmation commits once',async()=>{const h=await mount();try{const original=h.game;const before=h.pile();await act(()=>h.tray().props.onAdd(20,{current:null}));assert.equal(h.pile(),before-20);assert.equal(h.game,original);await act(()=>h.tray().props.onAdd(50,{current:null}));assert.equal(h.pile(),before-70);await act(()=>h.controls().props.onClear());assert.equal(h.pile(),before);await act(()=>h.tray().props.onAdd(50,{current:null}));const confirm=h.controls().props.onConfirm;await act(()=>{confirm();confirm();});await h.render();assert.equal(h.game.stacks.human,before-50);assert.equal(h.pile(),before-50);}finally{await h.close();}});
test('rapid selections respect cap and turn changes and exit discard provisional chips',async()=>{const h=await mount();try{const before=h.pile();const add=h.tray().props.onAdd;await act(()=>{for(let i=0;i<10;i++)add(100,{current:null});});assert.equal(h.pile(),before-900);assert.equal(h.r.root.findByType('PokerPot').props.amount-(h.game.total.human+h.game.total.computer),900);await h.setGame(engine.act(h.game,'human',{type:'call'}));assert.equal(h.pile(),h.game.stacks.human);await h.close();}catch(e){await h.close();throw e;}const next=await mount();try{assert.equal(next.pile(),next.game.stacks.human);}finally{await next.close();}});
test('screen fallback initializes only rival to 5000, retaining human selection and blinds',async()=>{const h=await mount(null);try{assert.equal(h.game.stacks.computer+h.game.total.computer,5000);assert.equal(h.game.stacks.human+h.game.total.human,3000);assert.equal(h.r.root.findByProps({testID:'poker-computer-pile'}).props.piles,3);assert.equal(h.r.root.findAllByProps({testID:'poker-player-pile'}).length,0);}finally{await h.close();}});
test('collection targets measured wood tray and presents settled credit only once',async()=>{const h=await mount(undefined,true);try{const before=h.game.stacks.human;await h.setGame({...h.game,street:'complete',stacks:{...h.game.stacks,human:before+850},result:{winner:'human',reason:'fold',pot:850}});const flight=h.r.root.findByType('ChipFlight');assert.deepEqual(flight.props.flight.to,{x:195,y:770});assert.equal(h.pile(),before);await act(()=>flight.props.onComplete());await h.render();assert.equal(h.pile(),before+850);assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.equal(h.r.root.findAllByProps({testID:'poker-player-pile'}).length,0);}finally{await h.close();}});
test('restart initializes same two seats and discards selection',async()=>{const h=await mount();try{await act(()=>h.tray().props.onAdd(50,{current:null}));await act(()=>h.r.root.findByType('TableSettings').props.onRules());const button=label=>h.r.root.findAllByType('Pressable').find(p=>p.findAllByType('Text').some(t=>t.props.children===label));await act(()=>button('Restart poker').props.onPress());await act(()=>button('Restart').props.onPress());await h.render();assert.equal(h.game.stacks.human+h.game.total.human,3000);assert.equal(h.game.stacks.computer+h.game.total.computer,5000);assert.equal(h.pile(),h.game.stacks.human);}finally{await h.close();}});
test('lobby start preserves all human starting options and existing match',async()=>{for(const human of [500,1000,2000,3000]){let game=null;const source=readFileSync(new URL('./CardGameLobby.tsx',import.meta.url),'utf8');const deps={react:React,'react-native':{View:'View',Text:'Text',Pressable:'Pressable',TextInput:'TextInput',ScrollView:'ScrollView'},'./engine':engine,'../components/LobbyGameHeader':{LobbyGameHeader:'LobbyGameHeader'},'../blackjack/BlackjackContext':{useBlackjack:()=>({})},'../nav/NavContext':{useNav:()=>({go(){},back(){}})},'../i18n/I18nContext':{useI18n:()=>({lang:'en'})},'../computer/ComputerGameContext':{useComputerGame:()=>({})},'../computer/OpponentChoices':{OpponentCarousel:'OpponentCarousel'},'../computer/tableTheme':{TABLE:{}},'@expo/vector-icons':{Feather:'Feather'},'../blackjack/ClassicPlayingCard':{ClassicPlayingCard:'Card'},'./TableGameContext':{useTableGame:()=>({pokerStartingChips:human,poker:game,setPoker:v=>game=v,enterMode(){}})}};const m={exports:{}};new Function('require','module','exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>deps[id],m,m.exports);let r;try{await act(()=>r=create(React.createElement(m.exports.CardGameLobby,{game:'poker'})));const play=label=>r.root.findAllByType('Pressable').find(p=>p.findAllByType('Text').some(t=>t.props.children===label));await act(()=>play('Play Poker').props.onPress());assert.equal(game.stacks.human+game.total.human,human);assert.equal(game.stacks.computer+game.total.computer,5000);const existing=game;await act(()=>r.update(React.createElement(m.exports.CardGameLobby,{game:'poker'})));await act(()=>play('Continue game').props.onPress());assert.equal(game,existing);}finally{await act(()=>r.unmount());}}});
test('lower-left pot and Clear Confirm share the new area without redundant raise captions; handoff preserves order and credits once',async()=>{const h=await mount();try{const before=h.pile();const pot=()=>h.r.root.findByType('PokerPot');assert.equal(pot().props.amount,30);await act(()=>h.tray().props.onAdd(50,{current:null}));const flight=h.r.root.findByType('ChipFlight');assert.equal(flight.props.flight.holdUntilLanding,true);assert.equal(pot().props.amount,80);assert.equal(pot().props.chips.reduce((sum,n)=>sum+n,0)+flight.props.flight.amount,80);const controls=h.r.root.findByProps({testID:'poker-selected-raise'});const spot=h.r.root.findByProps({testID:'poker-pot-spot'});assert.equal(controls.props.style.left+controls.props.style.width/2,spot.props.style.left+spot.props.style.width/2);assert.ok(controls.props.style.bottom<spot.props.style.bottom);assert.equal(controls.findAllByType('Text').length,0);await act(()=>flight.props.onComplete());assert.equal(h.r.root.findAllByType('ChipFlight').length,0);assert.deepEqual(pot().props.chips,[20,10,50]);const confirm=h.controls().props.onConfirm;await act(()=>{confirm();confirm();});await h.render();assert.equal(h.pile(),before-50);assert.equal(pot().props.amount,80);assert.deepEqual(pot().props.chips,[20,10,50]);}finally{await h.close();}});
