import {useHeldResultTimer} from '../components/useHeldResultTimer.ts';
import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {create,act} from 'react-test-renderer';import {readFileSync} from 'node:fs';import ts from 'typescript';import * as rebuy from './rebuy.ts';import {newHand} from './engine.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('./usePokerResultTransition.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(id=>id==='react'?React:id==='../components/useHeldResultTimer'?{useHeldResultTimer}:rebuy,m,m.exports);
test('3 visible seconds plus collected pot advances once, preserves stacks, pauses and cancels on exit; bankruptcy never invents credit',async()=>{
 const oldSet=setTimeout,oldClear=clearTimeout;let now=0,id=0,r,visible,nexts=[];const jobs=new Map();globalThis.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>jobs.delete(id);
 const base=newHand(undefined,()=>.3);const game={...base,hand:4,street:'complete',stacks:{human:800,computer:1200},result:{winner:'human',reason:'fold',pot:40}};
 function Probe({g=game,paused=false,collected=true}){visible=m.exports.usePokerResultTransition(g,paused,collected,n=>nexts.push(n));return null;}
 const render=async props=>act(()=>r?r.update(React.createElement(Probe,props)):r=create(React.createElement(Probe,props)));
 const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of jobs)if(j.at<=now){jobs.delete(key);j.fn();}});};
 try{
  await render({collected:false});assert.equal(visible,true);await tick(2999);assert.equal(visible,true);assert.equal(nexts.length,0);await tick(1);assert.equal(visible,false);assert.equal(nexts.length,0,'wait for chip flight');
  await render({});assert.equal(nexts.length,1);assert.equal(nexts[0].hand,5);assert.equal(nexts[0].stacks.human+nexts[0].bets.human,800);assert.equal(nexts[0].stacks.computer+nexts[0].bets.computer,1200);await render({});await tick(5000);assert.equal(nexts.length,1);
  const nextGame={...game,hand:5};await render({g:nextGame});await tick(1000);await render({g:nextGame,paused:true});await tick(5000);assert.equal(nexts.length,1);await render({g:nextGame});await tick(2999);assert.equal(nexts.length,1);await tick(1);assert.equal(nexts.length,2);
  const bankrupt={...game,hand:6,stacks:{human:0,computer:2000}};await render({g:bankrupt});await tick(3000);assert.equal(visible,false);assert.equal(nexts.length,2);assert.equal(bankrupt.stacks.human,0);
  await render({g:{...game,hand:7}});await act(()=>r.unmount());r=null;await tick(3000);assert.equal(nexts.length,2);assert.equal(jobs.size,0);
  await render({});assert.equal(visible,true);await tick(3000);assert.equal(nexts.length,3,'return presents result before one continuation');
 }finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;}
});
test('Hold preserves the remaining result time, keeps the outcome beyond three seconds, and release resumes once',async()=>{const oldSet=setTimeout,oldClear=clearTimeout,oldNow=Date.now;let now=0,id=0,r,visible;const jobs=new Map(),nexts=[],pressed={current:false};globalThis.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;};globalThis.clearTimeout=id=>jobs.delete(id);Date.now=()=>now;const game={...newHand(undefined,()=>.3),hand:8,result:{winner:'human',reason:'fold',pot:40},stacks:{human:1200,computer:800}};function Probe({held=false,collected=true}){visible=m.exports.usePokerResultTransition(game,false,collected,n=>nexts.push(n),held,pressed);return null;}const render=async p=>act(()=>r?r.update(React.createElement(Probe,p)):r=create(React.createElement(Probe,p)));const tick=async ms=>{now+=ms;await act(()=>{for(const [key,j] of jobs)if(j.at<=now){jobs.delete(key);j.fn();}});};try{await render({});await tick(1000);const late=[...jobs.values()][0].fn;pressed.current=true;await render({held:true});await tick(6000);await act(()=>late());assert.equal(visible,true);assert.equal(nexts.length,0);pressed.current=false;await render({});await tick(1999);assert.equal(visible,true);assert.equal(nexts.length,0);await tick(1);assert.equal(visible,false);assert.equal(nexts.length,1);await tick(5000);assert.equal(nexts.length,1);}finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;Date.now=oldNow;}});
test('Hold immediate ref blocks expiry before its state renders, and unmount cancels the held result',async()=>{const oldSet=setTimeout,oldClear=clearTimeout,oldNow=Date.now;let now=0,r,visible,nexts=0,fn;Date.now=()=>now;globalThis.setTimeout=callback=>{fn=callback;return 1;};globalThis.clearTimeout=()=>{};const pressed={current:false},game={...newHand(undefined,()=>.3),result:{winner:'human',reason:'fold',pot:40},stacks:{human:1200,computer:800}};function Probe({held=false}){visible=m.exports.usePokerResultTransition(game,false,true,()=>nexts++,held,pressed);return null;}try{await act(()=>r=create(React.createElement(Probe)));now=3000;pressed.current=true;await act(()=>fn());assert.equal(nexts,0);assert.equal(visible,true);await act(()=>r.update(React.createElement(Probe,{held:true})));await act(()=>r.unmount());r=null;pressed.current=false;await act(()=>fn());assert.equal(nexts,0);}finally{if(r)await act(()=>r.unmount());globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;Date.now=oldNow;}});
