export const LOBBY_RULES = {
  "poker": {
    "en": "Two private cards and five community cards. The best five-card hand wins.\n\nBlinds: 10 / 20. The button posts the small blind and acts first before the flop; the other player acts first afterward. Check, call, fold or raise up to your full stack.\n\nFlop: three cards. Turn and river: one each. An all-in runs out the board and compares hands. Raise amounts are the total bet for this street.",
    "es": "Dos cartas privadas y cinco comunitarias. Gana la mejor combinación de cinco cartas.\n\nCiegas: 10 / 20. El botón paga la ciega pequeña y actúa primero antes del flop; después actúa primero el rival. Puedes pasar, igualar, retirarte o subir hasta todas tus fichas.\n\nFlop: tres cartas. Turn y river: una más cada uno. En all-in se completa la mesa y se comparan las manos. El importe de subida es el total de esta calle."
  },
  "blackjack": {
    "en": "Reach 21 without going over. J/Q/K count 10; an ace counts 1 or 11. An ace and a ten-value card in the initial two cards are a natural blackjack, winning unless the dealer also has a natural (push). Hit adds a card; stand starts the dealer turn. The dealer hits through 16 and stands on all 17, including soft 17. Player bust loses immediately. Equal totals push. Fresh single deck each round. Virtual chips: wins pay 1:1 and natural blackjack 3:2. Double on the first decision doubles the wager, draws one card and stands. Repeat bet prepares the previous initial wager without dealing; Deal starts the round. No splitting or insurance.",
    "es": "Acércate a 21 sin pasarte. J/Q/K valen 10; el as vale 1 u 11. As y carta de valor 10 en las dos primeras cartas forman blackjack natural y ganan salvo otro natural (empate). Pedir añade una carta; plantarse inicia el turno del dealer. El dealer pide hasta 16 y se planta en todo 17, incluido el suave. Si te pasas, pierdes aunque el dealer pudiera pasarse. Totales iguales empatan. Una baraja nueva por ronda. Fichas virtuales: victoria paga 1:1 y blackjack natural 3:2. Doblar en la primera decisión duplica la apuesta, da una carta y planta la mano. Repetir prepara la apuesta inicial anterior sin repartir; Deal inicia la ronda. Sin dividir ni seguro."
  }
} as const;
