import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),React=require('react'),ts=require('typescript'),{act,create}=require('react-test-renderer');globalThis.IS_REACT_ACT_ENVIRONMENT=true;
for(const choice of ['rematch','new','home'])test(`finish overlay does not act on opening; ${choice} callback runs once`,async()=>{
 const calls=[];let r;const anim=()=>({start(){},stop(){}});
 const deps={react:React,'react-native':{Modal:'Modal',Text:'Text',View:'View',useWindowDimensions:()=>({width:320}),AccessibilityInfo:{isReduceMotionEnabled:async()=>true,addEventListener:()=>({remove(){}})},Easing:{cubic:x=>x,out:x=>x},Animated:{View:'AnimatedView',Value:class{stopAnimation(){}setValue(){}},timing:anim}},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:24,bottom:24})},'../theme/ThemeContext':{useTheme:()=>({theme:{colors:{}},s:n=>n})},'../i18n/I18nContext':{useI18n:()=>({lang:'en',t:{rematch:'rematch',newTeams:'new',backHome:'home'}})},'./ui':{Button:'Button'}};
 const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(new URL('./TrackingFinishDialog.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(id=>deps[id],m,m.exports);
 await act(async()=>{r=create(React.createElement(m.exports.TrackingFinishDialog,{visible:true,onRematch:()=>calls.push('rematch'),onNewMatch:()=>calls.push('new'),onHome:()=>calls.push('home')}));await Promise.resolve();});
 try{assert.deepEqual(calls,[]);const panel=r.root.findByProps({testID:'tracking-finish-popup'});assert.equal(r.root.findAllByType('Button').length,3);assert.equal(panel.findAllByType('Text').length,0);const button=r.root.findAllByType('Button').find(b=>b.props.label===choice);await act(()=>{button.props.onPress();button.props.onPress();});assert.deepEqual(calls,[choice]);}finally{await act(()=>r.unmount());}
});
